-- ============================================================
-- SECTION 1: SILVER_LAYER COMPLETE REBUILD
-- ============================================================

-- ============================================================
-- 1.1 SILVER_USER (NEW TABLE - GAP-001, GAP-007)
-- Grain: One row per user
-- Business Key: USER_ID
-- Source: BRONZE_LAYER.MST_TBLUSERS + MST_TBLDEPARTMENT + MST_TBLUSER_PROCESSROLES
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_USER` AS
      SELECT
        u.USER_ID, IFNULL(CAST(U.PUSER_ID AS INT64), 0) AS PARENT_USER_ID,
        TRIM(u.USER_EMPLOYEE_ID) AS USER_EMPLOYEE_ID,
        TRIM( INITCAP( REGEXP_REPLACE(u.USER_FIRSTNAME, r'[^A-Za-z0-9]+', ' ') ) ) AS USER_FIRSTNAME,
        TRIM( INITCAP( REGEXP_REPLACE(u.USER_MIDDLENAME, r'[^A-Za-z0-9]+', ' ') ) ) AS USER_MIDDLENAME,
        TRIM( INITCAP( REGEXP_REPLACE(u.USER_LASTNAME, r'[^A-Za-z0-9]+', ' ') ) ) AS USER_LASTNAME,
        TRIM( INITCAP( REGEXP_REPLACE( REGEXP_REPLACE(u.USER_FIRSTNAME, r'[^A-Za-z0-9]+', ' '), r'\s+', ' ' ) ) ) || 
        COALESCE( ' ' || TRIM( INITCAP( REGEXP_REPLACE( REGEXP_REPLACE(u.USER_LASTNAME, r'[^A-Za-z0-9]+', ' '), r'\s+', ' ' ) ) ), '' ) AS USER_FULL_NAME,
        CASE  WHEN REGEXP_CONTAINS(TRIM(LOWER(u.USER_EMAIL)),r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'  )  
            THEN TRIM(LOWER(u.USER_EMAIL))  ELSE   'Not Available' END AS USER_EMAIL,
        u.DEPARTMENT_ID,
        TRIM(d.DEPARTMENT_DESC) AS DEPARTMENT_DESC,
        u.PROLE_ID,
        TRIM(r.PROLE_DESC) AS PROCESS_ROLE_DESC,
        CASE WHEN NULLIF(TRIM(u.USER_COUNTRYCODE), '') IS NULL THEN NULL
        WHEN TRIM(u.USER_COUNTRYCODE) IN ('0', '00') THEN '00'
        WHEN REGEXP_CONTAINS(TRIM(u.USER_COUNTRYCODE), r'^\+?[0-9]{1,3}$')
        THEN REGEXP_REPLACE(TRIM(u.USER_COUNTRYCODE), r'^\+', '')
        ELSE '00' END AS USER_COUNTRYCODE ,
        CASE WHEN NULLIF(TRIM(u.USER_MOBILE), '') IS NULL THEN NULL
            WHEN REGEXP_CONTAINS(REGEXP_REPLACE(TRIM(u.USER_MOBILE), r'[^0-9]', ''),r'^[1-9][0-9]{9,14}$')  
            THEN REGEXP_REPLACE(TRIM(u.USER_MOBILE), r'[^0-9]', '')  ELSE '0000000000' END AS USER_MOBILE,
        u.ISWFH AS IS_WORK_FROM_HOME,
        u.ISCUSTOMACCESS AS IS_CUSTOM_ACCESS,
        u.ISATAQUALITYAUDITOR AS IS_QA_AUDITOR,
        u.PRDSUBGROUP_ID,u.P_ATA_ID,
        u.ISACTIVE AS IS_ACTIVE,
        CASE WHEN u.EXTENSION_ID IS NULL OR u.EXTENSION_ID <= 0 THEN '0' ELSE CAST(u.EXTENSION_ID AS STRING) END AS EXTENSION_ID,
        u.CREATED_DT,
        u.EDITED_DT,
        u.EDITED_BY,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.MST_TBLUSERS` u
    JOIN `BRONZE_LAYER_ODM.MST_TBLDEPARTMENT` d
        ON u.DEPARTMENT_ID = d.DEPARTMENT_ID
    JOIN `BRONZE_LAYER_ODM.MST_TBLUSER_PROCESSROLES` r
        ON u.PROLE_ID = r.PROLE_ID ;

-- ============================================================
-- 1.2 SILVER_LEAD (EXISTING - GAP-001 user name resolution, GAP-024 MULTI_UPLOADEDBY)
-- Grain: One row per lead
-- Business Key: LEAD_ID
-- ============================================================
CREATE TEMP FUNCTION CLEAN_TEXT(value STRING)
RETURNS STRING
LANGUAGE js AS """
  if (value === null) return null;

  return value
    .replace(/[^A-Za-z0-9]+/g, ' ')
    .replace(/(.)\\1{2,}/g, '$1')
    .trim();
""";
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_LEAD` AS
     WITH location_country AS (
        SELECT LOCATION_ID, TRIM(INITCAP(LOCATION_DESC)) AS LOCATION_DESC 
        FROM `BRONZE_LAYER.MST_TBLLOCATIONELEMENTS` WHERE LOCATION_TYPE = 'Country'
    ),
    location_state AS (
        SELECT LOCATION_ID, TRIM(INITCAP(LOCATION_DESC)) AS LOCATION_DESC 
        FROM `BRONZE_LAYER.MST_TBLLOCATIONELEMENTS` WHERE LOCATION_TYPE = 'State'
    ),
    location_city AS (
        SELECT LOCATION_ID, TRIM(INITCAP(LOCATION_DESC)) AS LOCATION_DESC 
        FROM `BRONZE_LAYER.MST_TBLLOCATIONELEMENTS` WHERE LOCATION_TYPE = 'City'
    )
    SELECT
        l.LEAD_ID,
        FARM_FINGERPRINT(CONCAT(UPPER(TRIM(REGEXP_REPLACE(REGEXP_REPLACE(l.COMPANY_NAME,r'[^\p{L}\p{N}\s]',' '),r'\s+',' '))),'|',CASE WHEN REGEXP_CONTAINS(TRIM(LOWER(l.MAIL_DOMAIN)),r'^[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN UPPER(TRIM(LOWER(l.MAIL_DOMAIN))) ELSE 'Not Available' END )) AS COMPANY_ID,
        TRIM( INITCAP( REGEXP_REPLACE(CLEAN_TEXT(l.FIRST_NAME), r'[^A-Za-z0-9]+', ' ') ) ) AS FIRST_NAME,
        TRIM( INITCAP( REGEXP_REPLACE(CLEAN_TEXT(l.LAST_NAME), r'[^A-Za-z0-9]+', ' ') ) ) AS LAST_NAME,
        l.SALUTATION_ID,
        s.SALUTATION_DESC AS SALUTATION_DESC,
        TRIM(INITCAP(REGEXP_REPLACE(CLEAN_TEXT(l.JOB_TITLE), r'[^A-Za-z]+', ' ')  )) AS JOB_TITLE,
        l.JOB_LEVEL_ID,
        jl.JOB_LEVEL_DESC AS JOB_LEVEL_DESC,
        l.JOBFUNCTION_ID,
        jf.JOBFUNCTION_DESC AS JOBFUNCTION_DESC,
        CASE WHEN l.TENURITY IS NULL THEN 'NA' WHEN REGEXP_CONTAINS(UPPER(l.TENURITY), 'HTTPS?://') THEN NULL
            ELSE CONCAT( COALESCE( NULLIF( REGEXP_REPLACE(REGEXP_EXTRACT(UPPER(l.TENURITY), r'[0-9]{1,3}[ ]*(?:YEAR|YEARS|YR|YRS|Y)'),'[^0-9]',''),''),'0'),' Years ',COALESCE(
            NULLIF(REGEXP_REPLACE(REGEXP_EXTRACT(UPPER(l.TENURITY),r'[0-9]{1,2}[ ]*(?:MONTH|MONTHS|MON|MONS|MOS|M)'),'[^0-9]',''),''),'0'),' Months') END AS TENURITY,
        CASE  WHEN REGEXP_CONTAINS(TRIM(LOWER(l.EMAIL_ID)),r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'  )  
            THEN TRIM(LOWER(l.EMAIL_ID))  ELSE   'Not Available' END AS EMAIL_ID,
        l.MD5_EMAIL_ID,
        CASE  WHEN REGEXP_CONTAINS(TRIM(LOWER(l.mail_domain)),r'^[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'  )  
            THEN TRIM(LOWER(l.mail_domain))  ELSE   'Not Available' END AS MAIL_DOMAIN,
        CASE WHEN NULLIF(TRIM(l.PHONE_NUMBER), '') IS NULL THEN '00000000' 
            WHEN REGEXP_CONTAINS( REGEXP_REPLACE( REGEXP_REPLACE(TRIM(l.PHONE_NUMBER), r'[^0-9]', ''), r'^0+', '' ), r'^[1-9][0-9]{6,14}$' ) 
            THEN REGEXP_REPLACE( REGEXP_REPLACE(TRIM(l.PHONE_NUMBER), r'[^0-9]', ''), r'^0+', '' ) ELSE '0000000000' END AS PHONE_NUMBER,
        CASE WHEN NULLIF(TRIM(l.COUNTRY_CODE), '') IS NULL THEN '00'
        WHEN TRIM(l.COUNTRY_CODE) IN ('0', '00') THEN '00'
        WHEN REGEXP_CONTAINS(TRIM(l.COUNTRY_CODE), r'^\+?[0-9]{1,3}$')
        THEN REGEXP_REPLACE(TRIM(l.COUNTRY_CODE), r'^\+', '')
        ELSE '00' END  AS COUNTRY_CODE,
        CASE WHEN NULLIF(TRIM(l.MOBILE_NO), '') IS NULL THEN '0000000000'
            WHEN REGEXP_CONTAINS(REGEXP_REPLACE(TRIM(l.MOBILE_NO), r'[^0-9]', ''),r'^[1-9][0-9]{9,14}$')  
            THEN REGEXP_REPLACE(TRIM(l.MOBILE_NO), r'[^0-9]', '')  ELSE '0000000000' END AS MOBILE_NO,
        CASE WHEN NULLIF(TRIM(l.DIRECT_DIAL_EXTENSION), '') IS NULL THEN '0'
            WHEN REGEXP_CONTAINS(TRIM(l.DIRECT_DIAL_EXTENSION), r'^[1-9][0-9]{0,5}$')
            THEN TRIM(l.DIRECT_DIAL_EXTENSION)  ELSE '0' END AS DIRECT_DIAL_EXTENSION,
        TRIM(REGEXP_REPLACE(REGEXP_REPLACE(COMPANY_NAME,r'[^\p{L}\p{N}\s]',' '),r'\s+',' ')) AS COMPANY_NAME,
        TRIM( INITCAP( REGEXP_REPLACE( REGEXP_REPLACE( l.ADDRESS1, r'[^\p{L}\p{N}\s.,/#()&-]', ' ' ), r'\s+', ' ' ) ) ) AS ADDRESS1,
        TRIM( INITCAP( REGEXP_REPLACE( REGEXP_REPLACE( l.ADDRESS2, r'[^\p{L}\p{N}\s.,/#()&-]', ' ' ), r'\s+', ' ' ) ) ) AS ADDRESS2,
        at_tag.ADDRESS_TAG_DESC AS ADDRESS_TAG_DESC,
        CASE WHEN NULLIF(TRIM(l.ZIP_CODE), '') IS NULL THEN 'Not Available' WHEN REGEXP_CONTAINS(
            TRIM(l.ZIP_CODE), r'^[A-Za-z0-9][A-Za-z0-9 -]{2,9}$' )THEN UPPER(TRIM(l.ZIP_CODE)) ELSE 'Not Available' END AS ZIP_CODE,
        l.COUNTRY_ID,
        lc.LOCATION_DESC AS COUNTRY_DESC,
        l.STATE_ID,
        ls.LOCATION_DESC AS STATE_DESC,
        l.CITY_ID,
        lci.LOCATION_DESC AS CITY_DESC,
        UPPER(TRIM(l.TIMEZONE_ABBR)) AS TIMEZONE_ABBR,
        TRIM(INITCAP( REGEXP_REPLACE(l.INDUSTRY, r'[^A-Za-z0-9]+', ' ') ) ) AS INDUSTRY,
        l.STANDARD_INDUSTRY_ID,
        si.STANDARD_INDUSTRY_DESC AS STANDARD_INDUSTRY_DESC,
        UPPER(TRIM(l.SIC_CODE)) AS SIC_CODE,
        UPPER(TRIM(l.NAICS_CODE)) AS NAICS_CODE,
        l.EMPLOYEE_SIZE_ID,
        es.EMPLOYEE_SIZE_DESC AS EMPLOYEE_SIZE_DESC,
        TRIM(l.ACTUAL_EMPLOYEE_SIZE) AS ACTUAL_EMPLOYEE_SIZE,
        l.REVENUE_SIZE_ID,
        rs.REVENUE_SIZE_DESC AS REVENUE_SIZE_DESC,
        l.CONTACT_SUCCESS_ATTEMPTS,
        l.DATAREUSE_ASIS_UNTIL_DT,
        l.ISMISUPLOAD AS IS_MIS_UPLOAD,
        l.ISUSERUPLOAD AS IS_USER_UPLOAD,
        l.ISPURCHASEDATA AS IS_PURCHASED_DATA,
        l.UPLOADED_DT,
        l.UPLOADED_BY,
        u_up.USER_FULL_NAME AS UPLOADED_BY_NAME,
        ARRAY_TO_STRING(REGEXP_EXTRACT_ALL(MULTI_UPLOADEDBY, r'\d+'),', ') AS MULTI_UPLOADED_BY,
        l.UNVR_ID,
        l.ORDERKEYID AS ORDER_KEY_ID_DIRECT,
        TRIM(LOWER(l.SUGGESTEDEMAIL_ID)) AS SUGGESTED_EMAIL_ID,
        l.ISDELETE AS IS_DELETED,
        l.EDITED_DT,
        l.EDITED_BY,
        u_ed.USER_FULL_NAME AS EDITED_BY_NAME,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.TBLLEADS_MASTERLIST` l
    INNER JOIN `BRONZE_LAYER.MST_TBLSALUTATION` s ON l.SALUTATION_ID = s.SALUTATION_ID
    INNER JOIN `BRONZE_LAYER.MST_TBLJOBLEVEL` jl ON l.JOB_LEVEL_ID = jl.JOB_LEVEL_ID
    INNER JOIN `BRONZE_LAYER.MST_TBLJOBFUNCTION` jf ON l.JOBFUNCTION_ID = jf.JOBFUNCTION_ID
    INNER JOIN `BRONZE_LAYER.MST_TBLADDRESSTAG` at_tag ON l.ADDRESS_TAG_ID = at_tag.ADDRESS_TAG_ID
    INNER JOIN location_country lc ON l.COUNTRY_ID = lc.LOCATION_ID
    INNER JOIN location_state ls ON l.STATE_ID = ls.LOCATION_ID
    INNER JOIN location_city lci ON l.CITY_ID = lci.LOCATION_ID
    INNER JOIN `BRONZE_LAYER.MST_TBLSTANDARDINDUSTRY` si ON l.STANDARD_INDUSTRY_ID = si.STANDARD_INDUSTRY_ID
    INNER JOIN `BRONZE_LAYER.MST_TBLEMPLOYEESIZE` es ON l.EMPLOYEE_SIZE_ID = es.EMPLOYEE_SIZE_ID
    INNER JOIN `BRONZE_LAYER.MST_TBLREVENUESIZE` rs ON l.REVENUE_SIZE_ID = rs.REVENUE_SIZE_ID
    INNER JOIN `SILVER_LAYER.SILVER_USER` u_up ON l.UPLOADED_BY = u_up.USER_ID
    INNER JOIN `SILVER_LAYER.SILVER_USER` u_ed ON l.EDITED_BY = u_ed.USER_ID    ;

-- ============================================================
-- 1.3 SILVER_COMPANY (EXISTING - unchanged)
-- Grain: One row per company (derived from leads)
-- Business Key: COMPANY_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_COMPANY` AS
    WITH company_base AS (
        SELECT
            FARM_FINGERPRINT(CONCAT(UPPER(TRIM(REGEXP_REPLACE(REGEXP_REPLACE(l.COMPANY_NAME,r'[^\p{L}\p{N}\s]',' '),r'\s+',' '))),'|',CASE WHEN REGEXP_CONTAINS(TRIM(LOWER(l.MAIL_DOMAIN)),r'^[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN UPPER(TRIM(LOWER(l.MAIL_DOMAIN))) ELSE 'Not Available' END )) AS COMPANY_ID,
            TRIM(REGEXP_REPLACE(REGEXP_REPLACE(COMPANY_NAME,r'[^\p{L}\p{N}\s]',' '),r'\s+',' ')) AS COMPANY_NAME,
            CASE  WHEN REGEXP_CONTAINS(TRIM(LOWER(l.mail_domain)),r'^[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'  )  
            THEN TRIM(LOWER(l.mail_domain))  ELSE   'Not Available' END AS MAIL_DOMAIN,
            TRIM(INITCAP( REGEXP_REPLACE(CLEAN_TEXT(l.INDUSTRY), r'[^A-Za-z0-9]+', ' ') ) ) AS INDUSTRY,
            l.STANDARD_INDUSTRY_ID,
            si.STANDARD_INDUSTRY_DESC AS STANDARD_INDUSTRY_DESC,
            TRIM(l.ACTUAL_EMPLOYEE_SIZE) AS ACTUAL_EMPLOYEE_SIZE,
            l.EMPLOYEE_SIZE_ID,
            es.EMPLOYEE_SIZE_DESC AS EMPLOYEE_SIZE_DESC,
            l.REVENUE_SIZE_ID,
            rs.REVENUE_SIZE_DESC AS REVENUE_SIZE_DESC,
            UPPER(TRIM(l.SIC_CODE)) AS SIC_CODE,
            UPPER(TRIM(l.NAICS_CODE)) AS NAICS_CODE,
        TRIM( INITCAP( REGEXP_REPLACE( REGEXP_REPLACE( l.ADDRESS1, r'[^\p{L}\p{N}\s.,/#()&-]', ' ' ), r'\s+', ' ' ) ) ) AS ADDRESS1,
        TRIM( INITCAP( REGEXP_REPLACE( REGEXP_REPLACE( l.ADDRESS2, r'[^\p{L}\p{N}\s.,/#()&-]', ' ' ), r'\s+', ' ' ) ) ) AS ADDRESS2,
            l.COUNTRY_ID,
            l.STATE_ID,
            l.CITY_ID,
            CASE WHEN NULLIF(TRIM(l.ZIP_CODE), '') IS NULL THEN 'Not Available' WHEN REGEXP_CONTAINS(
            TRIM(l.ZIP_CODE), r'^[A-Za-z0-9][A-Za-z0-9 -]{2,9}$' )THEN UPPER(TRIM(l.ZIP_CODE)) ELSE 'Not Available' END AS ZIP_CODE,
            l.UPLOADED_DT,
            l.EDITED_DT,
            ROW_NUMBER() OVER (PARTITION BY FARM_FINGERPRINT(CONCAT(UPPER(TRIM(REGEXP_REPLACE(REGEXP_REPLACE(l.COMPANY_NAME,r'[^\p{L}\p{N}\s]',' '),r'\s+',' '))),'|',CASE WHEN REGEXP_CONTAINS(TRIM(LOWER(l.MAIL_DOMAIN)),r'^[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN UPPER(TRIM(LOWER(l.MAIL_DOMAIN))) ELSE 'Not Available' END ))  ORDER BY l.EDITED_DT DESC NULLS LAST) AS RN
        FROM `BRONZE_LAYER.TBLLEADS_MASTERLIST` l
        inner JOIN `BRONZE_LAYER.MST_TBLSTANDARDINDUSTRY` si ON l.STANDARD_INDUSTRY_ID = si.STANDARD_INDUSTRY_ID
        inner JOIN `BRONZE_LAYER.MST_TBLEMPLOYEESIZE` es ON l.EMPLOYEE_SIZE_ID = es.EMPLOYEE_SIZE_ID
        inner JOIN `BRONZE_LAYER.MST_TBLREVENUESIZE` rs ON l.REVENUE_SIZE_ID = rs.REVENUE_SIZE_ID
        WHERE TRIM(l.COMPANY_NAME) !='' AND TRIM(l.MAIL_DOMAIN) != ''
    ),
    location_country AS (
        SELECT LOCATION_ID, TRIM(INITCAP(LOCATION_DESC)) AS LOCATION_DESC 
        FROM `BRONZE_LAYER.MST_TBLLOCATIONELEMENTS` WHERE LOCATION_TYPE = 'Country'
    ),
    location_state AS (
        SELECT LOCATION_ID, TRIM(INITCAP(LOCATION_DESC)) AS LOCATION_DESC 
        FROM `BRONZE_LAYER.MST_TBLLOCATIONELEMENTS` WHERE LOCATION_TYPE = 'State'
    ),
    location_city AS (
        SELECT LOCATION_ID, TRIM(INITCAP(LOCATION_DESC)) AS LOCATION_DESC 
        FROM `BRONZE_LAYER.MST_TBLLOCATIONELEMENTS` WHERE LOCATION_TYPE = 'City'
    ),
    company_agg AS (
        SELECT
            FARM_FINGERPRINT(CONCAT(UPPER(TRIM(REGEXP_REPLACE(REGEXP_REPLACE(COMPANY_NAME,r'[^\p{L}\p{N}\s]',' '),r'\s+',' '))),'|',CASE WHEN REGEXP_CONTAINS(TRIM(LOWER(MAIL_DOMAIN)),r'^[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN UPPER(TRIM(LOWER(MAIL_DOMAIN))) ELSE 'Not Available' END )) AS COMPANY_ID,    
            COUNT(*) AS LEAD_COUNT,
            MIN(UPLOADED_DT) AS FIRST_SEEN_DT,
            MAX(UPLOADED_DT) AS LAST_SEEN_DT
        FROM `BRONZE_LAYER.TBLLEADS_MASTERLIST`
        WHERE TRIM(COMPANY_NAME) != '' AND TRIM(MAIL_DOMAIN) != ''
        GROUP BY FARM_FINGERPRINT(CONCAT(UPPER(TRIM(REGEXP_REPLACE(REGEXP_REPLACE(COMPANY_NAME,r'[^\p{L}\p{N}\s]',' '),r'\s+',' '))),'|',CASE WHEN REGEXP_CONTAINS(TRIM(LOWER(MAIL_DOMAIN)),r'^[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN UPPER(TRIM(LOWER(MAIL_DOMAIN))) ELSE 'Not Available' END )) 
    )
    SELECT
        cb.COMPANY_ID,
        cb.COMPANY_NAME,
        cb.MAIL_DOMAIN,
        cb.INDUSTRY,
        cb.STANDARD_INDUSTRY_ID,
        cb.STANDARD_INDUSTRY_DESC,
        cb.ACTUAL_EMPLOYEE_SIZE,
        cb.EMPLOYEE_SIZE_ID,
        cb.EMPLOYEE_SIZE_DESC,
        cb.REVENUE_SIZE_ID,
        cb.REVENUE_SIZE_DESC,
        cb.SIC_CODE,
        cb.NAICS_CODE,
        cb.ADDRESS1,
        cb.ADDRESS2,
        cb.COUNTRY_ID,
        lc.LOCATION_DESC AS COUNTRY_DESC,
        cb.STATE_ID,
        ls.LOCATION_DESC AS STATE_DESC,
        cb.CITY_ID,
        lci.LOCATION_DESC AS CITY_DESC,
        cb.ZIP_CODE,
        ca.LEAD_COUNT,
        ca.FIRST_SEEN_DT,
        ca.LAST_SEEN_DT,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM company_base cb
    INNER JOIN location_country lc ON cb.COUNTRY_ID = lc.LOCATION_ID
    INNER JOIN location_state ls ON cb.STATE_ID = ls.LOCATION_ID
    INNER JOIN location_city lci ON cb.CITY_ID = lci.LOCATION_ID
    INNER JOIN company_agg ca ON cb.COMPANY_ID = ca.COMPANY_ID
    WHERE cb.RN = 1;

-- ============================================================
-- 1.4 SILVER_LEAD_ACTIVITY (EXISTING - GAP-001 INSERTED_BY_NAME)
-- Grain: One row per activity event
-- Business Key: RECORD_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_LEAD_ACTIVITY` AS
    SELECT
        t.RECORD_ID,
        t.LEAD_ID,
        t.ENGAGE_ID,
        t.OUTCOME_ID,
        o.OUTCOME_DESC,
        t.QASTATUS_ID,
        qs.QASTATUS_DESC AS QASTATUS_DESC,
        Initcap(TRIM(t.STATUS_SUPPORT_COMMENTS)) AS STATUS_SUPPORT_COMMENTS,
        t.ISCONTACTED AS IS_CONTACTED,
        t.ISSMTPQUALIFIED AS IS_SMTP_QUALIFIED,
        t.ISDELIVERED AS IS_DELIVERED,
        t.ISLIMBOINDICATOR AS IS_LIMBO_INDICATOR,
        t.LIMBO_END_DT,
        t.ISAUDITORLOCKED AS IS_AUDITOR_LOCKED,
        t.ISRERUN AS IS_RERUN,
        t.ISCURRENT AS IS_LATEST,
        t.ISCURRENT AS ISCURRENT_RAW,
        t.INSERTED_DT,
        t.INSERTED_BY,
        u.USER_FULL_NAME AS INSERTED_BY_NAME,
        e.CUSTOM_QUESTION_RESPONSE,
        TRIM( INITCAP( REGEXP_REPLACE(e.ASSETNAME, r'[^A-Za-z0-9]+', ' ') ) ) as ASSETNAME ,
        e.ISCONFIRMEDONCALL,
        e.TAL_RECORD_ID,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.TBLLEADS_STATUS_ACTIVITY_TRACKER` t
    INNER JOIN `BRONZE_LAYER.MST_TBLOUTCOMES` o ON t.OUTCOME_ID = o.OUTCOME_ID
    INNER JOIN `BRONZE_LAYER.MST_TBLQUALITYAUDIT_STATUS` qs ON t.QASTATUS_ID = qs.QASTATUS_ID
    INNER JOIN `BRONZE_LAYER.TBLENGAGED_LEADS` e ON t.ENGAGE_ID = e.ENGAGE_ID
    INNER JOIN `SILVER_LAYER.SILVER_USER` u ON t.INSERTED_BY = u.USER_ID;

-- ============================================================
-- 1.5 SILVER_ENGAGEMENT (NEW TABLE - GAP-002)
-- Grain: One row per engagement/call event
-- Business Key: ENGAGE_ID
-- Source: BRONZE_LAYER.TBLENGAGED_LEADS
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_ENGAGEMENT` AS
    SELECT
        e.ENGAGE_ID,
        e.CAMPAIGN_KEY_ID,
        e.ORDER_KEY_ID,
        e.LEAD_ID,
        TRIM(e.CUSTOM_QUESTION_RESPONSE) AS CUSTOM_QUESTION_RESPONSE,
        ARRAY_TO_STRING(REGEXP_EXTRACT_ALL(e.DNC_PHONE_NUMBERS, r'\d+'),', ') AS DNC_PHONE_NUMBERS,
        e.CALLBACK_SCHEDULE,
        CASE WHEN e.CALLBACK_SCHEDULE_ALERT  IS NULL THEN 'NA' ELSE e.CALLBACK_SCHEDULE_ALERT END AS CALLBACK_SCHEDULE_ALERT,
        e.LEADTYPE_ID,
        lt.LEADTYPE_DESC,
        e.OPS_LEADTYPE_ID,
        CASE WHEN olt.LEADTYPE_DESC IS NULL THEN 'Not Defined' ELSE olt.LEADTYPE_DESC END AS OPS_LEADTYPE_DESC,
        TRIM( INITCAP( REGEXP_REPLACE(e.ASSETNAME, r'[^A-Za-z0-9]+', ' ') ) ) as ASSETNAME ,
        TRIM( INITCAP( REGEXP_REPLACE(e.`ASSETNAME-EN`, r'[^A-Za-z0-9]+', ' ') ) ) as ASSETNAME_EN,
        TRIM(e.DIRECT_DIALED_NO) AS DIRECT_DIALED_NO,
        CASE WHEN NULLIF(TRIM(e.MOBILE_NO), '') IS NULL THEN '0000000000'
            WHEN REGEXP_CONTAINS(REGEXP_REPLACE(TRIM(e.MOBILE_NO), r'[^0-9]', ''),r'^[1-9][0-9]{9,14}$')  
            THEN REGEXP_REPLACE(TRIM(e.MOBILE_NO), r'[^0-9]', '')  ELSE '0000000000' END AS MOBILE_NO,
        CASE
            WHEN NULLIF(TRIM(e.EXTENSION_NO), '') IS NULL THEN 'NA'
            WHEN REGEXP_CONTAINS(TRIM(e.EXTENSION_NO), r'^[0-9]+$')
            THEN NULLIF(REGEXP_REPLACE(TRIM(e.EXTENSION_NO), r'^0+', ''), '') ELSE 'NA' END AS EXTENSION_NO,
        TRIM(e.REMARKS) AS REMARKS,
        e.ISCONFIRMEDONCALL AS IS_CONFIRMED_ON_CALL,
        e.ENGAGED_DT,
        e.ENGAGED_DT_IST,
        e.ENGAGED_DT_UTC,
        e.ENGAGED_BY,
        u.USER_FULL_NAME AS ENGAGED_BY_NAME,
        e.ISVALID AS IS_VALID,
        e.ISRECTIFIED AS IS_RECTIFIED,
        e.ISAUDITED AS IS_AUDITED,
        e.ISDELETE AS IS_DELETED,
        e.ISMISDISPOSE AS IS_MIS_DISPOSE,
        e.ISOT AS IS_OT,
        e.REFERENCE_ENGAGE_ID,
        e.TAL_RECORD_ID,
        e.ACTUAL_CALL_DURATION,
        e.OPS_VVSTSTUS_ID,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.TBLENGAGED_LEADS` e
    INNER JOIN `BRONZE_LAYER.MST_TBLLEADTYPES` lt ON e.LEADTYPE_ID = lt.LEADTYPE_ID
    INNER JOIN `BRONZE_LAYER.MST_TBLLEADTYPES` olt ON e.OPS_LEADTYPE_ID = olt.LEADTYPE_ID
    INNER JOIN `SILVER_LAYER.SILVER_USER` u ON e.ENGAGED_BY = u.USER_ID;


-- ============================================================
-- 1.6 SILVER_ORDER (EXISTING - GAP-003 FREQUENCY_DESC, GAP-004 REGION, GAP-005 CAMPAIGN_INFO, GAP-006 BRAND_INFO, GAP-014/015/016 address/PO)
-- Grain: One row per order
-- Business Key: ORDER_KEY_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_ORDER` AS
    WITH current_order_status AS (
        SELECT ORDER_KEY_ID, ORDERSTATUS_ID, ORDER_STATUS
        FROM (
            SELECT seg.ORDER_KEY_ID, osa.ORDERSTATUS_ID, os2.ORDER_STATUS,
                ROW_NUMBER() OVER (PARTITION BY seg.ORDER_KEY_ID ORDER BY osa.INSERTED_DT DESC) AS RN
            FROM `BRONZE_LAYER_ODM.TBLORDER_STATUS_ACTIVITY_TRACKER` osa
            INNER JOIN `BRONZE_LAYER_ODM.TBLORDER_SEGMENTS` seg ON osa.ORDER_SEGMENT_ID = seg.ORDER_SEGMENT_ID
            INNER JOIN `BRONZE_LAYER_ODM.MST_TBLORDER_STATUS` os2 ON osa.ORDERSTATUS_ID = os2.ORDERSTATUS_ID
        )
        WHERE RN = 1
    )
    SELECT
        b.ORDER_KEY_ID,
        UPPER(TRIM(b.ORDER_ID)) AS ORDER_ID,
        INITCAP(TRIM(b.ORDER_NAME)) AS ORDER_NAME,
        b.CAMPAIGN_KEY_ID,
        b.BRAND_ID,b.CLIENT_ACCTMNGR_ID ,
        CASE WHEN u_am.USER_FULL_NAME IS NULL THEN 'NA' ELSE u_am.USER_FULL_NAME END AS CLIENT_ACCTMNGR_NAME,
        case when odm.CLIENT_ID is null then 00 else odm.CLIENT_ID end as CLIENT_ID,
        UPPER(TRIM(b.ORDER_ID)) AS CLIENT_SOURCE,
        b.MODE_ID,
        UPPER(TRIM(m.MODE)) AS MODE_DESC,
        b.ORDERTYPE_ID,
        case when ot.ORDER_TYPE is null then 'NA' else ot.ORDER_TYPE end AS ORDER_TYPE_DESC,
        b.TACTIC_ID,
        tac.TACTIC_DESC AS TACTIC_DESC,
        b.INSERTION_ORDER_DT,
        UPPER(TRIM(b.INSERTION_ORDER_NUMBER)) AS INSERTION_ORDER_NUMBER,
        b.ORDER_MONTH,
        UPPER(TRIM(b.ORDER_REFID)) AS ORDER_REFID,
        b.INITIAL_TOTAL_QUANTITY,
        b.EFFECTIVE_TOTAL_QUANTITY,
        b.INITIAL_START_DELIVERY_DT,
        b.EFFECTIVE_END_DELIVERY_DT,
        b.PRICE,
        b.FREQUENCY_ID,
        f.FREQUENCY_SPECIFICATION AS FREQUENCY_DESC,
        case when os_cur.ORDERSTATUS_ID is null then 00 else os_cur.ORDERSTATUS_ID end AS CURRENT_ORDERSTATUS_ID,
        case when os_cur.ORDER_STATUS is null then 'Not Defined' else os_cur.ORDER_STATUS end AS CURRENT_ORDER_STATUS_DESC,
        case when odm.TOTAL_COST_USD is null then 00 else odm.TOTAL_COST_USD end as TOTAL_COST_USD,
        case when odm.TOTAL_COST_CCY is null then 00 else odm.TOTAL_COST_CCY end as TOTAL_COST_CCY,
        CASE WHEN CC.CURRENCY_CODE IS NULL THEN 'NA' ELSE UPPER(TRIM(CC.CURRENCY_CODE)) END AS CLIENT_CURRENCY_CODE,
        CASE WHEN odm.IO_PO_NUMBER IS NULL THEN 'NA' ELSE UPPER(TRIM(odm.IO_PO_NUMBER)) END AS IO_PO_NUMBER,
        CASE WHEN odm.INVOICE_REFERENCES IS NULL THEN 'NA' ELSE UPPER(TRIM(odm.INVOICE_REFERENCES)) END AS INVOICE_REFERENCES,
        CASE WHEN odm.REGION_ID IS NULL THEN 00 ELSE odm.REGION_ID END AS REGION_ID,
        CASE WHEN reg.REGION_DESC IS NULL THEN 'NA' ELSE UPPER(TRIM(reg.REGION_DESC)) END AS REGION_DESC,
        CASE WHEN odm.CAMPAIGN_INFORMATION IS NULL THEN 'NA' ELSE UPPER(TRIM(odm.CAMPAIGN_INFORMATION)) END AS CAMPAIGN_INFORMATION,
        CASE WHEN odm.BRAND_INFORMATION IS NULL THEN 'NA' ELSE UPPER(TRIM(odm.BRAND_INFORMATION)) END AS BRAND_INFORMATION,
        CASE WHEN odm.CONTACT_ADDR_ID IS NULL THEN 00 ELSE odm.CONTACT_ADDR_ID END AS CONTACT_ADDR_ID,
        CASE WHEN odm.BILLING_ADDR_ID IS NULL THEN 00 ELSE odm.BILLING_ADDR_ID END AS BILLING_ADDR_ID,
        CASE WHEN odm.PO_WO_REFERENCES IS NULL THEN 'NA' ELSE UPPER(TRIM(odm.PO_WO_REFERENCES)) END AS PO_WO_REFERENCES,
        CASE WHEN dp.FIN_YEAR IS NULL THEN 0000 ELSE dp.FIN_YEAR END AS ODM_ORDER_FISCAL_YEAR,
        CASE WHEN dp.FIN_QR  IS NULL THEN 0 ELSE dp.FIN_QR END AS ODM_ORDER_FISCAL_QUARTER,
        b.ISACTIVE AS IS_ACTIVE,
        b.ISORDERLIVE AS IS_ORDER_LIVE,
        b.ISRECTIFIED AS IS_RECTIFIED,
        b.ISREVIEWED AS IS_REVIEWED,
        b.CREATED_DT,
        b.EDITED_DT,
        b.EDITED_BY,
        u_ed.USER_FULL_NAME AS EDITED_BY_NAME,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.TBLORDER_DETAILS` b
    LEFT JOIN `BRONZE_LAYER_ODM.TBLORDER_DETAILS` odm ON b.ORDER_KEY_ID = odm.ORDER_KEY_ID
    INNER JOIN `BRONZE_LAYER.MST_TBLORDER_MODE` m ON b.MODE_ID = m.MODE_ID  
    INNER JOIN `BRONZE_LAYER.MST_TBLORDERTYPE` ot ON b.ORDERTYPE_ID = ot.ORDERTYPE_ID -- SIMILAR TABLES IN ODM
    INNER JOIN `BRONZE_LAYER.MST_TBLORDER_TACTICS` tac ON b.TACTIC_ID = tac.TACTIC_ID   -- SIMILAR TABLES IN ODM
    INNER JOIN `BRONZE_LAYER.MST_TBLDELIVERY_FREQUENCY` f ON b.FREQUENCY_ID = f.FREQUENCY_ID
    LEFT JOIN `BRONZE_LAYER_ODM.MST_TBLREGIONS` reg ON odm.REGION_ID = reg.REGION_ID
    LEFT JOIN `BRONZE_LAYER_ODM.MST_TBLCURRENCYCODES` cc ON odm.CLIENT_CURRENCY = cc.CURRENCY_ID
    LEFT JOIN `BRONZE_LAYER_ODM.TBLORDER_DATEPARAM` dp ON b.ORDER_KEY_ID = dp.ORDER_KEY_ID
    INNER JOIN `SILVER_LAYER.SILVER_USER` u_am ON b.CLIENT_ACCTMNGR_ID = u_am.USER_ID
    INNER JOIN `SILVER_LAYER.SILVER_USER` u_ed ON b.EDITED_BY = u_ed.USER_ID
    LEFT JOIN current_order_status os_cur ON b.ORDER_KEY_ID = os_cur.ORDER_KEY_ID;

-- ============================================================
-- 1.7 SILVER_TARGETING (EXISTING - unchanged)
-- Grain: One row per targeting param set
-- Business Key: ORDER_KEY_ID + PARAM_RECORD_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_TARGETING` AS
    SELECT
        t.ORDER_KEY_ID,
        t.RECORD_ID AS PARAM_RECORD_ID,
        CASE WHEN TRIM(t.PARAM1) IS NULL THEN 'NA' ELSE TRIM(t.PARAM1) END AS PARAM1,
        CASE WHEN TRIM(t.PARAM2) IS NULL THEN 'NA' ELSE TRIM(t.PARAM2) END AS PARAM2,
        CASE WHEN TRIM(t.PARAM3) IS NULL THEN 'NA' ELSE TRIM(t.PARAM3) END AS PARAM3,
        CASE WHEN TRIM(t.PARAM4) IS NULL THEN 'NA' ELSE TRIM(t.PARAM4) END AS PARAM4,
        t.HASASSET AS HAS_ASSET,
        TRIM(t.ORDER_FOLDER_DATE) AS ORDER_FOLDER_DATE,
        t.MOD_INDICATOR,
        t.ISREVENUERESTRICTED AS IS_REVENUE_RESTRICTED,
        t.ISSCRIPTREQUIRED AS IS_SCRIPT_REQUIRED,
        CASE WHEN pt.RECORD_ID IS NULL THEN 00 ELSE pt.RECORD_ID END AS PERFORMANCE_TARGET_RECORD_ID,
        CASE WHEN TRIM(pt.PERFORMANCE_TARGET_PARAMETERS) IS NULL THEN 'NA' ELSE TRIM(pt.PERFORMANCE_TARGET_PARAMETERS) END AS PERFORMANCE_TARGET_PARAMETERS,
        CASE WHEN pt.ISEDITLOCKED IS NULL THEN FALSE ELSE pt.ISEDITLOCKED END AS IS_PERFORMANCE_TARGET_LOCKED,
        CASE WHEN supp.SUPPRESSION_RULE_COUNT IS NULL THEN 0 ELSE supp.SUPPRESSION_RULE_COUNT END AS SUPPRESSION_RULE_COUNT,
        t.ISDELETE AS IS_DELETED,
        t.EDITED_DT,
        t.EDITED_BY,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.TBLORDERSPECIFICATIONPARAM_DETAILS` t
    LEFT JOIN `BRONZE_LAYER.TBLPERFORMANCETARGET_DETAILS` pt ON pt.ORDER_KEY_ID = t.ORDER_KEY_ID
    LEFT JOIN (
        SELECT ORDER_KEY_ID, COUNT(*) AS SUPPRESSION_RULE_COUNT
        FROM `BRONZE_LAYER.TBLORDERSPECIFIC_DATASUPRESSION_TBD`
        WHERE COALESCE(ISACTIVE, TRUE) = TRUE
        GROUP BY ORDER_KEY_ID
    ) supp ON supp.ORDER_KEY_ID = t.ORDER_KEY_ID;

-- ============================================================
-- 1.8 SILVER_ORDER_SEGMENT (EXISTING - GAP-001 user name)
-- Grain: One row per segment
-- Business Key: ORDER_SEGMENT_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_ORDER_SEGMENT` AS
    SELECT
        s.ORDER_SEGMENT_ID,
        s.ORDER_KEY_ID,
        s.SEGMENT_ORDER,
        s.TYPE_TACTIC_ID AS TACTIC_ID,
        upper(trim(tac.TACTIC_DESC)) AS TACTIC_DESC,
        cc.CURRENCY_CODE AS CLIENT_CURRENCY_CODE,
        s.ISDELIVERYDT_TBD AS IS_DELIVERY_DT_TBD,
        s.SEGMENTSTATUS_ID,
        os.ORDER_STATUS AS SEGMENT_STATUS_DESC,
        s.INITIAL_TOTAL_QUANTITY,
        s.EFFECTIVE_TOTAL_QUANTITY,
        s.TOTAL_COST_CCY,
        s.TOTAL_COST_USD,
        s.TOTAL_BILLED,
        UPPER(TRIM(s.CAMPAIGN_CODE)) AS CAMPAIGN_CODE,
        s.INSERTED_DT,
        s.INSERTED_BY,
        u_ins.USER_FULL_NAME AS INSERTED_BY_NAME,
        s.EDITED_DT,
        s.EDITED_BY,
        u_ed.USER_FULL_NAME AS EDITED_BY_NAME,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER_ODM.TBLORDER_SEGMENTS` s
    LEFT JOIN `BRONZE_LAYER.MST_TBLORDER_TACTICS` tac ON s.TYPE_TACTIC_ID = tac.TACTIC_ID -- SIMILAR TABLE EXISTS IN ODM
    LEFT JOIN `BRONZE_LAYER.MST_TBLORDER_STATUS` os ON s.SEGMENTSTATUS_ID = os.ORDERSTATUS_ID -- SIMILAR TABLE EXISTS IN ODM 
    LEFT JOIN `BRONZE_LAYER_ODM.MST_TBLCURRENCYCODES` cc ON s.CLIENT_CURRENCY = cc.CURRENCY_ID
    LEFT JOIN `SILVER_LAYER.SILVER_USER` u_ins ON s.INSERTED_BY = u_ins.USER_ID
    LEFT JOIN `SILVER_LAYER.SILVER_USER` u_ed ON s.EDITED_BY = u_ed.USER_ID;
-- ============================================================
-- 1.9 SILVER_ORDER_SEGMENT_TARGETING (EXISTING - unchanged)
-- Grain: One row per segment targeting record
-- Business Key: RECORD_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_ORDER_SEGMENT_TARGETING` AS
    SELECT
        t.RECORD_ID,
        t.ORDER_SEGMENT_ID,
        TRIM(t.PARAM1) AS PARAM1,
        TRIM(t.PARAM2) AS PARAM2,
        TRIM(t.PARAM3) AS PARAM3,
        TRIM(t.PARAM4) AS PARAM4,
        TRIM(t.PARAM5) AS PARAM5,
        TRIM(t.PARAM6) AS PARAM6,
        t.ISDELETE AS IS_DELETED,
        t.EDITED_DT,
        t.EDITED_BY,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER_ODM.TBLORDERSPECIFICATIONPARAM_DETAILS` t;

-- ============================================================
-- 1.10 SILVER_ORDER_SEGMENT_STATUS_HISTORY (EXISTING - GAP-001 INSERTED_BY_NAME)
-- Grain: One row per status change event
-- Business Key: RECORD_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_ORDER_SEGMENT_STATUS_HISTORY` AS
    SELECT
        t.RECORD_ID,
        t.ORDER_SEGMENT_ID,
        t.ORDERSTATUS_ID,
        os.ORDER_STATUS AS ORDER_STATUS_DESC,
        TRIM(t.STATUS_SUPPORT_STATEMENT) AS STATUS_SUPPORT_STATEMENT,
        CASE WHEN t.ISCURRENT = TRUE THEN TRUE ELSE FALSE END AS IS_LATEST,
        t.ISCURRENT AS ISCURRENT_RAW,
        t.INSERTED_DT,
        t.INSERTED_BY,
        u.USER_FULL_NAME AS INSERTED_BY_NAME,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER_ODM.TBLORDER_STATUS_ACTIVITY_TRACKER` t
    LEFT JOIN `BRONZE_LAYER_ODM.MST_TBLORDER_STATUS` os ON t.ORDERSTATUS_ID = os.ORDERSTATUS_ID
    LEFT JOIN `SILVER_LAYER.SILVER_USER` u ON t.INSERTED_BY = u.USER_ID;

-- ============================================================
-- 1.11 SILVER_ORDER_ADJUDICATION (EXISTING - GAP-011/012 date types fixed)
-- Grain: One row per adjudication
-- Business Key: ADJUDICATE_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_ORDER_ADJUDICATION` AS
    SELECT
        a.ADJUDICATE_ID,
        a.ORDER_SEGMENT_ID,
        a.QUANTITY,
        a.CPL_CCY,
        a.CPL_USD,
        a.EFFECTIVE_QUANTITY,
        CAST(a.START_DELIVERY_DT AS DATE) AS START_DELIVERY_DT,
        CAST(a.END_DELIVERY_DT AS DATE) AS END_DELIVERY_DT,
        TRIM(a.ORDER_INSTANCE) AS ORDER_INSTANCE,
        a.ISACTIVE AS IS_ACTIVE,
        a.ISDELETE AS IS_DELETED,
        a.CREATED_DT,
        a.EDITED_DT,
        a.EDITED_BY,
        u.USER_FULL_NAME AS EDITED_BY_NAME,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER_ODM.TBLORDER_ADJUDICATION` a
    LEFT JOIN `SILVER_LAYER.SILVER_USER` u ON a.EDITED_BY = u.USER_ID;

-- ============================================================
-- 1.12 SILVER_ORDER_HEADER_HISTORY (EXISTING - GAP-001 EDITED_BY_NAME)
-- Grain: One row per header change
-- Business Key: TRACK_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_ORDER_HEADER_HISTORY` AS
    SELECT
        t.TRACK_ID,
        t.ORDER_KEY_ID,
        t.CLIENT_ID,
        t.INSERTION_ORDER_DT,
        TRIM(t.INSERTION_ORDER_NUMBER) AS INSERTION_ORDER_NUMBER,
        t.TOTAL_COST_CCY,
        t.TOTAL_COST_USD,
        UPPER(TRIM(t.IO_PO_NUMBER)) AS IO_PO_NUMBER,
        t.EDITED_DT,
        t.EDITED_BY,
        u.USER_FULL_NAME AS EDITED_BY_NAME,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER_ODM.TBLORDER_DETAILS_TRACKER` t
    LEFT JOIN `SILVER_LAYER.SILVER_USER` u ON t.EDITED_BY = u.USER_ID;

-- ============================================================
-- 1.13 SILVER_ORDER_PACING (EXISTING - unchanged)
-- Grain: One row per pacing record
-- Business Key: PACING_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_ORDER_PACING` AS
    SELECT
        p.PACING_ID,
        p.ORDER_SEGMENT_ID,
        p.PACING_SET_DT,
        p.PACING_SET_COUNT,
        p.PACING_DONE_COUNT,
        p.PACING_COMPLETE,
        p.REASON_ID,
        case when pr.REASON_NAME is null then 'Not Available' else pr.REASON_NAME end as REASON_NAME,
        p.PACING_ENABLE,
        p.EDITED_DT,
        p.EDITED_BY,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER_ODM.TBLOPS_PACING_DETAILS` p
    LEFT JOIN `BRONZE_LAYER_ODM.MST_TBLPACINGREASONS` pr ON p.REASON_ID = pr.REASON_ID;

-- ============================================================
-- 1.14 SILVER_ORDER_INVOICE (EXISTING - unchanged)
-- Grain: One row per invoice
-- Business Key: INVOICE_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_ORDER_INVOICE` AS
    SELECT
        i.INVOICE_ID,
        i.ORDER_KEY_ID,
        i.ORDER_SEGMENT_ID,
        UPPER(TRIM(i.INVOICE_NUMBER)) AS INVOICE_NUMBER,
        i.INVOICE_DT,
        i.INVOICE_AMOUNT,
        i.PAID_STATUS,
        i.ISDELETE AS IS_DELETED,
        i.CREATED_DT,
        i.EDITED_DT,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER_ODM.TBLORDERINVOICE_DETAILS` i;

-- ============================================================
-- 1.15 SILVER_ORDER_DELIVERY_OPS (EXISTING - unchanged)
-- Grain: One row per delivery ops campaign record
-- Business Key: OPS_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_ORDER_DELIVERY_OPS` AS
    SELECT
        d.OPS_ID,
        d.ORDER_SEGMENT_ID,
        d.OPSSTATUS_ID,
        d.OPS_START_DT,
        d.OPS_END_DT,
        d.ODM_QUALIFIED,
        d.ODM_DELIVERED,
        d.CLIENT_REJECTED,
        d.CLIENT_ACCEPTED,
        d.LEAD_PROCESSING,
        d.AUDIT_PENDING,
        d.OPS_LEADS,
        d.OPS_TOTAL_DEFICT AS OPS_TOTAL_DEFICIT,
        d.DAYS_LEFT,
        d.DAYS_ELAPSED,
        d.DAYS_FOR_CAMPAIGN,
        d.OPS_TARGET_PER_DAY,
        d.PROGRAM_COMPLETION,
        d.PROGRAM_HEALTH,
        INITCAP(TRIM(d.OPS_COMMENT)) AS OPS_COMMENT,
        INITCAP(TRIM(d.PACING_COMMENT)) AS PACING_COMMENT,
        d.EDITED_DT,
        d.EDITED_BY,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER_ODM.TBLOPS_DELIVERY_CAMPAIGN_DETAILS` d;

-- ============================================================
-- 1.16 SILVER_DELIVERY (EXISTING - GAP-001 UPLOADED_BY_NAME)
-- Grain: One row per delivery record
-- Business Key: RECORD_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_DELIVERY` AS
    WITH delivery_lead_map AS (
        SELECT RECORD_ID, LEAD_ID
        FROM `BRONZE_LAYER.TBLLEADS_STATUS_ACTIVITY_TRACKER`
        QUALIFY ROW_NUMBER() OVER (PARTITION BY RECORD_ID ORDER BY INSERTED_DT DESC, RECORD_ID DESC) = 1
    )
    SELECT
        d.RECORD_ID,
        dlm.LEAD_ID,
        TRIM(d.ORDER_ID) AS ORDER_ID,
        UPPER(TRIM(d.CLIENT_NAME)) AS CLIENT_NAME,
        UPPER(TRIM(d.CAMPAIGN_NAME)) AS CAMPAIGN_NAME,
        d.DELIVERY_DT,
        TRIM( INITCAP( REGEXP_REPLACE(d.FIRSTNAME, r'[^A-Za-z0-9]+', ' ') ) ) AS FIRSTNAME,
        TRIM( INITCAP( REGEXP_REPLACE(d.LASTNAME, r'[^A-Za-z0-9]+', ' ') ) ) AS LASTNAME,
        TRIM(REGEXP_REPLACE(REGEXP_REPLACE(COMPANY_NAME,r'[^\p{L}\p{N}\s]',' '),r'\s+',' ')) AS COMPANY_NAME,
        CASE WHEN (TRIM(d.PHONE_NUMBER), '') IS NULL THEN '0000000000'
            WHEN REGEXP_CONTAINS(REGEXP_REPLACE(TRIM(d.PHONE_NUMBER), r'[^0-9]', ''),r'^[1-9][0-9]{9,14}$')  
            THEN REGEXP_REPLACE(TRIM(d.PHONE_NUMBER), r'[^0-9]', '')  ELSE '0000000000' END AS PHONE_NUMBER,
        CASE WHEN REGEXP_CONTAINS(TRIM(LOWER(EMAIL_ID)),r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'  )  
            THEN TRIM(LOWER(EMAIL_ID))  ELSE   'Not Available' END AS EMAIL_ID, 
        CASE WHEN REGEXP_CONTAINS(TRIM(LOWER(MAIL_DOMAIN)),r'[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'  )  
            THEN TRIM(LOWER(MAIL_DOMAIN))  ELSE   'Not Available' END AS MAIL_DOMAIN, 
        TRIM(d.LEADTYPE_DESC) AS LEADTYPE_DESC,
        TRIM(d.JOB_TITLE_LINK) AS JOB_TITLE_LINK,
        d.UPLOADED_DT,
        d.UPLOADED_BY,
        u.USER_FULL_NAME AS UPLOADED_BY_NAME,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.TBLMISDELIVERED_LEADS` d
     JOIN delivery_lead_map dlm ON dlm.RECORD_ID = d.RECORD_ID
     JOIN `SILVER_LAYER.SILVER_USER` u ON d.UPLOADED_BY = u.USER_ID;

-- ============================================================
-- 1.17 SILVER_MISDELIVERY (EXISTING - GAP-001 UPLOADED_BY_NAME)
-- Grain: One row per misdelivery record
-- Business Key: RECORD_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_MISDELIVERY` AS
    SELECT
        d.RECORD_ID,
        TRIM(d.ORDER_ID) AS ORDER_ID,
        UPPER(TRIM(d.CLIENT_NAME)) AS CLIENT_NAME,
        UPPER(TRIM(d.CAMPAIGN_NAME)) AS CAMPAIGN_NAME,
        d.DELIVERY_DT,
        TRIM( INITCAP( REGEXP_REPLACE(d.FIRSTNAME, r'[^A-Za-z0-9]+', ' ') ) ) AS FIRSTNAME,
        TRIM( INITCAP( REGEXP_REPLACE(d.LASTNAME, r'[^A-Za-z0-9]+', ' ') ) ) AS LASTNAME,
        TRIM(REGEXP_REPLACE(REGEXP_REPLACE(COMPANY_NAME,r'[^\p{L}\p{N}\s]',' '),r'\s+',' ')) AS COMPANY_NAME,
        CASE WHEN NULLIF(TRIM(d.PHONE_NUMBER), '') IS NULL THEN '0000000000'
            WHEN REGEXP_CONTAINS(REGEXP_REPLACE(TRIM(d.PHONE_NUMBER), r'[^0-9]', ''),r'^[1-9][0-9]{9,14}$')  
            THEN REGEXP_REPLACE(TRIM(d.PHONE_NUMBER), r'[^0-9]', '')  ELSE '0000000000' END AS PHONE_NUMBER,
        CASE WHEN REGEXP_CONTAINS(TRIM(LOWER(EMAIL_ID)),r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'  )  
            THEN TRIM(LOWER(EMAIL_ID))  ELSE   'Not Available' END AS EMAIL_ID, 
        CASE WHEN REGEXP_CONTAINS(TRIM(LOWER(MAIL_DOMAIN)),r'[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'  )  
            THEN TRIM(LOWER(MAIL_DOMAIN))  ELSE   'Not Available' END AS MAIL_DOMAIN, 
        TRIM(d.LEADTYPE_DESC) AS LEAD_TYPE_DESC,
        TRIM(d.JOB_TITLE_LINK) AS JOB_TITLE,
        d.UPLOADED_BY,
        u.USER_FULL_NAME AS UPLOADED_BY_NAME,
        d.UPLOADED_DT,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.TBLMISDELIVERED_LEADS` d
    LEFT JOIN `SILVER_LAYER.SILVER_USER` u ON d.UPLOADED_BY = u.USER_ID;

-- ============================================================
-- 1.18 SILVER_QA (EXISTING - unchanged)
-- Grain: One row per QA audit record
-- Business Key: RECORD_ID
-- ============================================================
 WITH qa_answer_counts AS (
        SELECT ENGAGE_ID, COUNT(*) AS QUALIFYING_ANSWER_COUNT
        FROM `BRONZE_LAYER.TBLAUDITPROFILINGQUALIFYINGANSWERS`
        GROUP BY ENGAGE_ID
    )
    SELECT
        q.RECORD_ID,
        q.ENGAGE_ID,
        q.AUDITSTATUS_ID,
        qs.QASTATUS_DESC AS AUDITSTATUS_DESC,
        q.PRIMARYREASON_ID,
        pr.QAPRIMARYREASON_DESC AS PRIMARYREASON_DESC,
        q.SECONDARYREASON_ID,
        q.CALLRATING_ID,
        cr.QACALLRATING_DESC AS CALLRATING_DESC,
        q.SEGMENT_ID,
        sg.QASEGMENT_DESC AS SEGMENT_DESC,
        q.CALLSTATUS_ID,
        cs.CALL_STATUS AS CALLSTATUS_DESC,
        INITCAP(TRIM(q.COMMENTS)) AS COMMENTS,
        TRIM(q.VERIFIEDNUMBER) AS VERIFIEDNUMBER,
        q.PRODUCTIVITY,
        q.LEAD_GENERATION_DATE,
        CASE WHEN q.CALL_DURATION IS NULL THEN 'NA' ELSE q.CALL_DURATION END AS CALL_DURATION,
        COALESCE(qac.QUALIFYING_ANSWER_COUNT, 0) AS QUALIFYING_ANSWER_COUNT,
        q.REWORKABLE,
        q.ISDELETE AS IS_DELETED,
        q.EDITED_DT,
        q.EDITED_BY,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.TBLQUALITYAUDIT_DETAILS` q
     JOIN `BRONZE_LAYER.MST_TBLQUALITYAUDIT_STATUS` qs ON q.AUDITSTATUS_ID = qs.QASTATUS_ID
     JOIN `BRONZE_LAYER.MST_TBLQUALITYAUDIT_PRIMARY_REASON` pr ON q.PRIMARYREASON_ID = pr.QAPRIMARYREASON_ID
     JOIN `BRONZE_LAYER.MST_TBLQUALITYAUDIT_CALLRATING` cr ON q.CALLRATING_ID = cr.QACALLRATING_ID
     JOIN `BRONZE_LAYER.MST_TBLQUALITYAUDIT_SEGMENT` sg ON q.SEGMENT_ID = sg.QASEGMENT_ID
     JOIN `BRONZE_LAYER.MST_TBLQUALITYAUDIT_CALLSTATUS` cs ON q.CALLSTATUS_ID = cs.CALLSTATUS_ID
    LEFT JOIN qa_answer_counts qac ON q.ENGAGE_ID = qac.ENGAGE_ID;


-- ============================================================
-- 1.19 SILVER_SMTP (EXISTING - GAP-001 UPLOADED_BY_NAME)
-- Grain: One row per SMTP verification
-- Business Key: RECORD_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_SMTP` AS
     WITH smtp_engage_map AS (
        SELECT TRIM(LOWER(EMAIL_ID))AS EMAIL_ID, CLIENT_ID, LEAD_ID, ENGAGE_ID, CAMPAIGN_KEY_ID
        FROM `BRONZE_LAYER.TBLSMTP_ENGAGE_MAPPING`
        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY EMAIL_ID, CLIENT_ID
            ORDER BY ID DESC
        ) = 1
    )
    SELECT
        s.RECORD_ID,
        m.LEAD_ID,
        m.ENGAGE_ID,
        m.CAMPAIGN_KEY_ID,
        s.CLIENT_ID,
            CASE WHEN REGEXP_CONTAINS(TRIM(LOWER(S.EMAIL_ID)),r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'  )  
            THEN TRIM(LOWER(S.eMAIL_ID))  ELSE   'Not Available' END AS EMAIL_ID,
        s.IDATE,
        TRIM(s.REASON_CODE) AS REASON_CODE,
        (CASE WHEN s.TOOL1_STATUS IS NOT NULL THEN 1 ELSE 0 END +
        CASE WHEN s.TOOL2_STATUS IS NOT NULL THEN 1 ELSE 0 END +
        CASE WHEN s.TOOL3_STATUS IS NOT NULL THEN 1 ELSE 0 END +
        CASE WHEN s.TOOL4_STATUS IS NOT NULL THEN 1 ELSE 0 END +
        CASE WHEN s.TOOL5_STATUS IS NOT NULL THEN 1 ELSE 0 END +
        CASE WHEN s.TOOL6_STATUS IS NOT NULL THEN 1 ELSE 0 END +
        CASE WHEN s.TOOL7_STATUS IS NOT NULL THEN 1 ELSE 0 END +
        CASE WHEN s.TOOL8_STATUS IS NOT NULL THEN 1 ELSE 0 END) AS VERIFICATION_TOOL_COUNT,
        TRIM(s.FINAL_STATUS) AS FINAL_STATUS,
        TRIM( INITCAP( REGEXP_REPLACE(S.EBB_TEAM, r'[^A-Za-z0-9]+', ' ') ) ) AS EBB_TEAM,
        LOWER(TRIM(s.SLOT_TYPE)) AS SLOT_TYPE,
        TRIM(s.SLOT_TIME) AS SLOT_TIME,
        s.AUTOUPLOAD_DT,
        s.UPLOADED_DT,
        s.UPLOADED_BY,
        u.USER_FULL_NAME AS UPLOADED_BY_NAME,
        s.ISVERIFICATIONTERMEXPIRED AS IS_VERIFICATION_TERM_EXPIRED,
        s.ISDELETE AS IS_DELETED,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.TBLSMTPAUDIT_DETAILS_V3` s
     JOIN smtp_engage_map m ON TRIM(LOWER(s.EMAIL_ID)) = m.EMAIL_ID AND s.CLIENT_ID = m.CLIENT_ID
     JOIN `SILVER_LAYER.SILVER_USER` u ON s.UPLOADED_BY = u.USER_ID;
-- ============================================================
-- 1.20 SILVER_BRAND (EXISTING - unchanged)
-- Grain: One row per brand
-- Business Key: BRAND_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_BRAND` AS
    SELECT
        b.BRAND_ID,
        TRIM(INITCAP(REGEXP_REPLACE(B.BRAND_NAME, r'[^A-Za-z0-9]+', ' '))) AS BRAND_NAME,
        b.CLIENT_ID,
        b.ISACTIVE AS IS_ACTIVE,
        b.CREATED_DT,
        b.EDITED_DT,
        b.EDITED_BY,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.MST_TBLCLIENT_BRANDS` b;

-- ============================================================
-- 1.21 SILVER_CAMPAIGN (EXISTING - unchanged)
-- Grain: One row per campaign
-- Business Key: CAMPAIGN_KEY_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_CAMPAIGN` AS
    SELECT
        c.CAMPAIGN_KEY_ID,
        UPPER(TRIM(c.CAMPAIGN_ID)) AS CAMPAIGN_ID,
        TRIM(c.CAMPAIGN_DESC) AS CAMPAIGN_DESC,
        c.CLIENT_ID,
        c.ISACTIVE AS IS_ACTIVE,
        c.CREATED_DT,
        c.EDITED_DT,
        c.EDITED_BY,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.MST_TBLCLIENT_CAMPAIGNS` c;

-- ============================================================
-- 1.22 SILVER_CLIENT (EXISTING - GAP-001 user name resolution for acct managers)
-- Grain: One row per client
-- Business Key: CLIENT_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_CLIENT` AS
    SELECT
        c.CLIENT_ID,
        TRIM( INITCAP( REGEXP_REPLACE(C.CLIENT_NAME, r'[^A-Za-z0-9]+', ' ') ) ) AS  CLIENT_NAME,
        TRIM( UPPER( REGEXP_REPLACE(C.CLIENT_PSEUDONAME, r'[^A-Za-z0-9]+', ' ') ) ) AS CLIENT_PSEUDONAME,
        TRIM( INITCAP( REGEXP_REPLACE(C.SALES_MANAGER, r'[^A-Za-z0-9]+', ' ') ) ) AS SALES_MANAGER,
        c.REGION_ID,
        reg.FYTARGET,
        c.INDIA_ACCTMN_ID,
        c.INTL_ACCTMN_ID,
        TRIM(reg.REGION_DESC) AS REGION_DESC,
        c.PAYMENTTERM_ID,
        TRIM(pt.PAYMENTTERM_DESC) AS PAYMENTTERM_DESC,
        c.PREFERENCE_ID,
        TRIM(bp.PREFERENCE_DESC) AS PREFERENCE_DESC,
        c.ISACTIVE AS IS_ACTIVE,
        'ODM' AS SOURCE_SYSTEM,
        c.CREATED_DT,
        c.EDITED_DT,
        c.EDITED_BY,
        u_ed.USER_FULL_NAME AS EDITED_BY_NAME,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER_ODM.MST_TBLCLIENTS` c
    JOIN `BRONZE_LAYER_ODM.MST_TBLREGIONS` reg ON c.REGION_ID = reg.REGION_ID
    JOIN `BRONZE_LAYER_ODM.MST_TBLPAYMENTTERMS` pt ON c.PAYMENTTERM_ID = pt.PAYMENTTERM_ID
    JOIN `BRONZE_LAYER_ODM.MST_TBLBILLINGPREFERENCES` bp ON c.PREFERENCE_ID = bp.PREFERENCE_ID
    LEFT JOIN `SILVER_LAYER.SILVER_USER` u_ed ON c.EDITED_BY = u_ed.USER_ID;

-- ============================================================
-- 1.23 SILVER_CLIENT_ADDRESS (EXISTING - unchanged)
-- Grain: One row per client address
-- Business Key: CLIENT_ID + ADDRESS_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_CLIENT_ADDRESS` AS
    WITH location_country AS (
        SELECT LOCATION_ID, TRIM(INITCAP(LOCATION_DESC)) AS LOCATION_DESC 
        FROM `BRONZE_LAYER_ODM.MST_TBLLOCATIONELEMENTS` WHERE LOCATION_TYPE = 'Country'
    ),
    location_state AS (
        SELECT LOCATION_ID, TRIM(INITCAP(LOCATION_DESC)) AS LOCATION_DESC 
        FROM `BRONZE_LAYER_ODM.MST_TBLLOCATIONELEMENTS` WHERE LOCATION_TYPE = 'State'
    ),
    location_city AS (
        SELECT LOCATION_ID, TRIM(INITCAP(LOCATION_DESC)) AS LOCATION_DESC 
        FROM `BRONZE_LAYER_ODM.MST_TBLLOCATIONELEMENTS` WHERE LOCATION_TYPE = 'City'
    )
    SELECT
        cam.CLIENT_ID,
        a.ADDRESS_ID,
        TRIM(a.CLIENT_ADDRESS_TYPE) AS CLIENT_ADDRESS_TYPE,
        TRIM(INITCAP(a.FIRSTNAME)) AS FIRSTNAME,
        TRIM(INITCAP(a.LASTNAME)) AS LASTNAME,
        TRIM(UPPER(REGEXP_REPLACE(a.DESIGNATION,r'[^A-Za-z0-9]+', ' ')) ) AS DESIGNATION,
        TRIM(INITCAP(REGEXP_REPLACE(a.STREET_ADDRESS, r'[^A-Za-z0-9]+', ' '))) AS STREET_ADDRESS,
        a.CITY_ID,
        lci.LOCATION_DESC AS CITY_DESC,
        a.STATE_ID,
        ls.LOCATION_DESC AS STATE_DESC,
        a.COUNTRY_ID,
        lc.LOCATION_DESC AS COUNTRY_DESC,
        TRIM(a.COUNTRYCODE) AS COUNTRYCODE,
        UPPER(TRIM(a.ZIPCODE)) AS ZIPCODE,
        TRIM(REGEXP_REPLACE(a.PHONE, r'[^A-Za-z0-9,]+', ' ')) AS PHONE,
        CASE WHEN REGEXP_CONTAINS(TRIM(LOWER(EMAILID)),r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN TRIM(LOWER(EMAILID)) ELSE 'Not Available' END  AS EMAILID,
        a.EDITED_DT,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER_ODM.MST_TBLCLIENTS_ADDRESSES` a
    JOIN `BRONZE_LAYER_ODM.MST_TBLCLIENTADDRMAPPING` cam ON a.ADDRESS_ID = cam.ADDRESS_ID
    JOIN location_country lc ON a.COUNTRY_ID = lc.LOCATION_ID
    JOIN location_state ls ON a.STATE_ID = ls.LOCATION_ID
    JOIN location_city lci ON a.CITY_ID = lci.LOCATION_ID
    WHERE a.ISACTIVE = TRUE;

-- ============================================================
-- 1.24 SILVER_SUPPRESSION (EXISTING - GAP-001 INSERTED_BY_NAME)
-- Grain: One row per suppression record
-- Business Key: SUPRESS_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_SUPPRESSION` AS
    SELECT
        s.SUPRESS_ID,
        s.ENGAGE_ID,
        s.LEAD_ID,
        TRIM(sr.SUPRESSREASON_DESC) AS SUPPRESSION_REASON,
        s.SUPRESSREASON_ID,
        CASE 
            WHEN s.SUPRESSREASON_ID = 1 THEN 'Contact_Limit'
            WHEN s.SUPRESSREASON_ID = 2 THEN 'DNC'
            WHEN s.SUPRESSREASON_ID = 3 THEN 'Dead Contact'
            WHEN s.SUPRESSREASON_ID IN (4, 5) THEN 'Invalid Phone'
            WHEN s.SUPRESSREASON_ID = 6 THEN 'Out of Office'
            WHEN s.SUPRESSREASON_ID = 7 THEN 'Rectify CD'
            WHEN s.SUPRESSREASON_ID = 8 THEN 'EBB'
            WHEN s.SUPRESSREASON_ID = 9 THEN 'QA Red Flag'
            ELSE 'Other'
        END AS SUPPRESSION_CATEGORY,
        s.ISINDEFINITESUPRESSED AS IS_INDEFINITE,
        s.SUPRESS_UNTIL_DT,
        s.INSERTED_DT,
        s.INSERTED_BY,
        u.USER_FULL_NAME AS INSERTED_BY_NAME,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.TBLLEADS_SUPRESSION` s
    LEFT JOIN `BRONZE_LAYER.MST_TBLLEADSUPRESS_REASON` sr ON s.SUPRESSREASON_ID = sr.SUPRESSREASON_ID
    LEFT JOIN `SILVER_LAYER.SILVER_USER` u ON s.INSERTED_BY = u.USER_ID;

-- ============================================================
-- 1.25 SILVER_LEAD_PATTERN (NEW TABLE - GAP-008)
-- Grain: One row per lead pattern record
-- Business Key: RECORD_ID
-- Source: BRONZE_LAYER.TBLLEADS_PATTERN
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_LEAD_PATTERN` AS
    SELECT
        p.RECORD_ID,
        p.LEAD_ID,
        TRIM(INITCAP(REGEXP_REPLACE(LEAD_PATTERNS, r'[^A-Za-z0-9,]+', ' '))) AS LEAD_PATTERNS,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.TBLLEADS_PATTERN` p;


-- ============================================================
-- 1.26 SILVER_LEAD_HISTORY (NEW TABLE - GAP-013)
-- Grain: One row per lead change event
-- Business Key: TRACK_ID
-- Source: BRONZE_LAYER.TBLLEADS_MASTERLIST_TRACKER
-- ============================================================

----------------------------------------------------------------------------------------------------START HERE----------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------21082026-------------------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_LEAD_HISTORY` AS
    WITH location_country AS (
        SELECT LOCATION_ID, TRIM(INITCAP(LOCATION_DESC)) AS LOCATION_DESC 
        FROM `BRONZE_LAYER.MST_TBLLOCATIONELEMENTS` WHERE LOCATION_TYPE = 'Country'
    ),
    location_state AS (
        SELECT LOCATION_ID, TRIM(INITCAP(LOCATION_DESC)) AS LOCATION_DESC 
        FROM `BRONZE_LAYER.MST_TBLLOCATIONELEMENTS` WHERE LOCATION_TYPE = 'State'
    ),
    location_city AS (
        SELECT LOCATION_ID, TRIM(INITCAP(LOCATION_DESC)) AS LOCATION_DESC 
        FROM `BRONZE_LAYER.MST_TBLLOCATIONELEMENTS` WHERE LOCATION_TYPE = 'City'
    )
    SELECT
        t.TRACK_ID,
        t.LEAD_ID,
        CASE  WHEN REGEXP_CONTAINS(TRIM(LOWER(t.mail_domain)),r'^[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'  )  
            THEN TRIM(LOWER(t.MAIL_DOMAIN))  ELSE   NULL END AS MAIL_DOMAIN,
        TRIM(REGEXP_REPLACE(REGEXP_REPLACE(t.COMPANY_NAME,r'[^\p{L}\p{N}\s]',' '),r'\s+',' ')) AS COMPANY_NAME,
        TRIM(INITCAP( REGEXP_REPLACE(t.INDUSTRY, r'[^A-Za-z0-9]+', ' ') ) ) AS INDUSTRY,
        t.STANDARD_INDUSTRY_ID,
        TRIM(t.SIC_CODE) AS SIC_CODE,
        TRIM(t.NAICS_CODE) AS NAICS_CODE,
        t.EMPLOYEE_SIZE_ID,
        TRIM(t.ACTUAL_EMPLOYEE_SIZE) AS ACTUAL_EMPLOYEE_SIZE,
        t.REVENUE_SIZE_ID,
        t.ADDRESS_TAG_ID,
        TRIM( INITCAP( REGEXP_REPLACE( REGEXP_REPLACE( t.ADDRESS1, r'[^\p{L}\p{N}\s.,/#()&-]', ' ' ), r'\s+', ' ' ) ) ) AS ADDRESS1,
        TRIM( INITCAP( REGEXP_REPLACE( REGEXP_REPLACE( t.ADDRESS2, r'[^\p{L}\p{N}\s.,/#()&-]', ' ' ), r'\s+', ' ' ) ) ) AS ADDRESS2,
        t.COUNTRY_ID,
        lc.LOCATION_DESC AS COUNTRY_DESC,
        t.STATE_ID,
        ls.LOCATION_DESC AS STATE_DESC,
        t.CITY_ID,
        lci.LOCATION_DESC AS CITY_DESC,
        CASE WHEN NULLIF(TRIM(t.ZIP_CODE), '') IS NULL THEN NULL WHEN REGEXP_CONTAINS(
        TRIM(t.ZIP_CODE), r'^[A-Za-z0-9][A-Za-z0-9 -]{2,9}$' )THEN UPPER(TRIM(t.ZIP_CODE)) ELSE NULL END AS ZIP_CODE,
        t.SALUTATION_ID,
        TRIM(INITCAP(REGEXP_REPLACE(t.FIRST_NAME,r'[^A-Za-z0-9]+',' '))) AS FIRST_NAME,
        TRIM(INITCAP(REGEXP_REPLACE(t.LAST_NAME,r'[^A-Za-z0-9]+',' '))) AS LAST_NAME,
        CASE WHEN NULLIF(TRIM(t.COUNTRY_CODE), '') IS NULL THEN NULL WHEN TRIM(t.COUNTRY_CODE) IN ('0', '00') THEN NULL
            WHEN REGEXP_CONTAINS(TRIM(t.COUNTRY_CODE), r'^\+?[0-9]{1,3}$') THEN REGEXP_REPLACE(TRIM(t.COUNTRY_CODE), r'^\+', '')
            ELSE NULL END  AS COUNTRY_CODE,
        CASE WHEN NULLIF(TRIM(t.PHONE_NUMBER), '') IS NULL THEN NULL 
            WHEN REGEXP_CONTAINS( REGEXP_REPLACE( REGEXP_REPLACE(TRIM(t.PHONE_NUMBER), r'[^0-9]', ''), r'^0+', '' ), r'^[1-9][0-9]{6,14}$' ) 
            THEN REGEXP_REPLACE( REGEXP_REPLACE(TRIM(t.PHONE_NUMBER), r'[^0-9]', ''), r'^0+', '' ) ELSE NULL END AS PHONE_NUMBER,
        CASE WHEN NULLIF(TRIM(t.MOBILE_NO), '') IS NULL THEN NULL
            WHEN REGEXP_CONTAINS(REGEXP_REPLACE(TRIM(t.MOBILE_NO), r'[^0-9]', ''),r'^[1-9][0-9]{9,14}$')  
            THEN REGEXP_REPLACE(TRIM(t.MOBILE_NO), r'[^0-9]', '')  ELSE NULL END AS MOBILE_NO,
        CASE WHEN NULLIF(TRIM(t.DIRECT_DIAL_EXTENSION), '') IS NULL THEN NULL
            WHEN REGEXP_CONTAINS(TRIM(t.DIRECT_DIAL_EXTENSION), r'^[1-9][0-9]{0,5}$')
            THEN TRIM(t.DIRECT_DIAL_EXTENSION)  ELSE NULL END AS DIRECT_DIAL_EXTENSION,
        CASE  WHEN REGEXP_CONTAINS(TRIM(LOWER(t.EMAIL_ID)),r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'  )  
            THEN TRIM(LOWER(t.EMAIL_ID))  ELSE   NULL END AS EMAIL_ID,
        TRIM(INITCAP(REGEXP_REPLACE(t.JOB_TITLE, r'[^A-Za-z0-9]+', ' ')  )) AS JOB_TITLE,
        CASE WHEN t.TENURITY IS NULL THEN NULL WHEN REGEXP_CONTAINS(UPPER(t.TENURITY), 'HTTPS?://') THEN NULL
            ELSE CONCAT( COALESCE( NULLIF( REGEXP_REPLACE(REGEXP_EXTRACT(UPPER(t.TENURITY), r'[0-9]{1,3}[ ]*(?:YEAR|YEARS|YR|YRS|Y)'),'[^0-9]',''),''),'0'),' Years ',COALESCE(
            NULLIF(REGEXP_REPLACE(REGEXP_EXTRACT(UPPER(t.TENURITY),r'[0-9]{1,2}[ ]*(?:MONTH|MONTHS|MON|MONS|MOS|M)'),'[^0-9]',''),''),'0'),' Months') END AS TENURITY,
        t.JOB_LEVEL_ID,
        t.JOBFUNCTION_ID,
        TRIM(t.TIMEZONE_ABBR) AS TIMEZONE_ABBR,
        t.ISMISUPLOAD AS IS_MIS_UPLOAD,
        t.ISUSERUPLOAD AS IS_USER_UPLOAD,
        t.UPLOADED_DT,
        t.UPLOADED_BY,
        u_up.USER_FULL_NAME AS UPLOADED_BY_NAME,
        t.EDITED_DT,
        t.EDITED_BY,
        u_ed.USER_FULL_NAME AS EDITED_BY_NAME,
        t.ISDELETE AS IS_DELETED,
        t.CONTACT_SUCCESS_ATTEMPTS,
        t.DATAREUSE_ASIS_UNTIL_DT,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.TBLLEADS_MASTERLIST_TRACKER` t
    JOIN `location_country` lc ON t.COUNTRY_ID = lc.LOCATION_ID
    JOIN `location_state` ls ON t.STATE_ID = ls.LOCATION_ID
    JOIN `location_city` lci ON t.CITY_ID = lci.LOCATION_ID
    JOIN `SILVER_LAYER.SILVER_USER` u_up ON t.UPLOADED_BY = u_up.USER_ID
    JOIN `SILVER_LAYER.SILVER_USER` u_ed ON t.EDITED_BY = u_ed.USER_ID;

-- ============================================================
-- 1.27 SILVER_DELIVERY_SCHEDULE (NEW TABLE - GAP-017)
-- Grain: One row per schedule entry
-- Business Key: RECORD_ID
-- Source: BRONZE_LAYER.TBLORDER_DELIVERY_SCHEDULE_GUIDE
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_DELIVERY_SCHEDULE` AS
    SELECT
        s.RECORD_ID,
        s.ORDER_KEY_ID,
        s.SCHEDULED_DT,
        s.SCHEDULED_QUANTITY,
        TRIM(s.ORDER_INSTANCE) AS ORDER_INSTANCE,
        s.ISAUTOGENERATED AS IS_AUTO_GENERATED,
        s.ISMANUAL AS IS_MANUAL,
        s.ISSCHEDULEREVISED AS IS_SCHEDULE_REVISED,
        TRIM(s.SCHEDULE_REVISION_NOTES) AS SCHEDULE_REVISION_NOTES,
        s.CREATED_DT,
        s.EDITED_DT,
        s.EDITED_BY,
        u.USER_FULL_NAME AS EDITED_BY_NAME,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.TBLORDER_DELIVERY_SCHEDULE_GUIDE` s
    LEFT JOIN `SILVER_LAYER.SILVER_USER` u ON s.EDITED_BY = u.USER_ID;

-- ============================================================
-- 1.28 SILVER_ORDER_FTE (NEW TABLE - GAP-018)
-- Grain: One row per FTE allocation record
-- Business Key: RECORD_ID
-- Source: BRONZE_LAYER.TBLORDER_FTEDISTRIBUTION
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_ORDER_FTE` AS
    SELECT
        f.RECORD_ID,
        f.ATTENDANCE_ID,
        f.ORDER_KEY_ID,
        f.FTE,
        f.PRECONSUMED_FTE,
        f.ISEDITABLE AS IS_EDITABLE,
        f.ISCURRENT AS IS_CURRENT,
        f.IND_FTE,
        f.EDITED_DT,
        f.EDITED_BY,
        u.USER_FULL_NAME AS EDITED_BY_NAME,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.TBLORDER_FTEDISTRIBUTION` f
    LEFT JOIN `SILVER_LAYER.SILVER_USER` u ON f.EDITED_BY = u.USER_ID;

-- ============================================================
-- 1.29 SILVER_EXCHANGE_RATE (NEW TABLE - GAP-023)
-- Grain: One row per currency-date
-- Business Key: CONVERSION_ID
-- Source: BRONZE_LAYER_ODM.TBLDAILYCONVERSIONRATE_USD
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_EXCHANGE_RATE` AS
    SELECT
        cr.CONVERSION_ID,
        cr.CURRENCY_ID,
        TRIM(UPPER(cr.CURRENCY_CODE)) AS CURRENCY_CODE,
        cr.CONVERSION_DATE,
        cr.USD_RATE,
        cr.ISACTIVE AS IS_ACTIVE,
        cr.INSERTED_DT AS CREATED_DT,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER_ODM.TBLDAILYCONVERSIONRATE_USD` cr;

-- ============================================================
-- 1.30 SILVER_SUPPRESSION_HISTORY (NEW TABLE - GAP-021)
-- Grain: One row per suppression change
-- Business Key: TRACK_ID
-- Source: BRONZE_LAYER.TBLLEADS_SUPRESSION_TRACKER
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_SUPPRESSION_HISTORY` AS
    SELECT
        t.TRACK_ID,
        t.SUPRESS_ID,
        t.LEAD_ID,
        t.ENGAGE_ID,
        t.SUPRESSREASON_ID,
        t.ISINDEFINITESUPRESSED AS IS_INDEFINITE_SUPPRESSED,
        t.SUPRESS_UNTIL_DT,
        t.SUPRESSION_REMOVAL_DT,
        t.INSERTED_DT,
        t.INSERTED_BY,
        u.USER_FULL_NAME AS INSERTED_BY_NAME,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.TBLLEADS_SUPRESSION_TRACKER` t
    LEFT JOIN `SILVER_LAYER.SILVER_USER` u ON t.INSERTED_BY = u.USER_ID;

-- ============================================================
-- 1.31 SILVER_QA_QUALIFYING_ANSWERS (NEW TABLE - GAP-027)
-- Grain: One row per qualifying answer
-- Business Key: PQANSWER_ID
-- Source: BRONZE_LAYER.TBLAUDITPROFILINGQUALIFYINGANSWERS
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_QA_QUALIFYING_ANSWERS` AS
    SELECT
        a.PQANSWER_ID,
        a.AUDTIRECORD_ID AS AUDIT_RECORD_ID,
        a.ENGAGE_ID,
        a.SEQUENCENUMBER AS SEQUENCE_NUMBER,
        TRIM(a.PROFILING) AS PROFILING,
        TRIM(a.QUALIFYING) AS QUALIFYING,
        a.INSERTED_DT,
        a.INSERTED_BY,
        u.USER_FULL_NAME AS INSERTED_BY_NAME,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.TBLAUDITPROFILINGQUALIFYINGANSWERS` a
    LEFT JOIN `SILVER_LAYER.SILVER_USER` u ON a.INSERTED_BY = u.USER_ID;

-- ============================================================
-- 1.32 SILVER_TAL_RECORD (NEW TABLE - GAP-028)
-- Grain: One row per TAL record
-- Business Key: TAL_RECORD_ID
-- Source: BRONZE_LAYER.TAL_UPLOADDED_RECORDS
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_TAL_RECORD` AS
    SELECT
        t.TAL_RECORD_ID,
        t.TAL_ID,
        TRIM(REGEXP_REPLACE(REGEXP_REPLACE(t.COMPANY,r'[^\p{L}\p{N}\s]',' '),r'\s+',' ')) AS COMPANY ,
        CASE WHEN REGEXP_CONTAINS(TRIM(LOWER(DOMAIN)),r'^[A-Za-z0-9.-]+\.[A-Za-z]{2,}$' ) THEN TRIM(LOWER(DOMAIN))  ELSE   NULL END AS DOMAIN,
        t.FOLLOWED_BY,
        u.USER_FULL_NAME AS FOLLOWED_BY_NAME,
        TRIM(INITCAP(t.COUNTRY_NAME)) AS COUNTRY_NAME,
        t.DOMAIN_LIMIT,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.TAL_UPLOADDED_RECORDS` t
    LEFT JOIN `SILVER_LAYER.SILVER_USER` u ON t.FOLLOWED_BY = u.USER_ID;

-- ============================================================
-- 1.33 SILVER_ATTENDANCE (NEW TABLE - GAP-031)
-- Grain: One row per user-day
-- Business Key: ATTENDANCE_ID
-- Source: BRONZE_LAYER.TBLDAILY_ATTENDANCE
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_ATTENDANCE` AS
    SELECT
        a.ATTENDANCE_ID,
        a.USER_ID,
        u.USER_FULL_NAME AS USER_NAME,
        u.DEPARTMENT_DESC,
        a.ATTENDANCE_DATE,
        a.PRODUCTION_HOURS,
        a.CALCULATED_FTE,
        a.ISCURRENT AS IS_CURRENT,
        a.TZ AS TIMEZONE_OFFSET,
        TRIM(a.ACTIVITY_KEY_ID) AS ACTIVITY_KEY_ID,
        a.SHIFT_TZ AS SHIFT_TIMEZONE,
        a.EDITED_DT,
        a.EDITED_BY,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.TBLDAILY_ATTENDANCE` a
    LEFT JOIN `SILVER_LAYER.SILVER_USER` u ON a.USER_ID = u.USER_ID;

-- ============================================================
-- 1.34 SILVER_RECORDING (NEW TABLE - GAP-033)
-- Grain: One row per recording
-- Business Key: RECORD_ID
-- Source: BRONZE_LAYER.TBLRECORDINGDETAILS
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_RECORDING` AS
    SELECT
        r.RECORD_ID,
        r.USERID AS USER_ID,
        u.USER_FULL_NAME AS USER_NAME,
        r.LEAD_ID,
        r.ORDER_KEY_ID,
        TRIM(r.CHANNELNAME) AS CHANNEL_NAME,
        r.AGENTEXTEN AS AGENT_EXTENSION,
        r.CDATE AS RECORDING_DT,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.TBLRECORDINGDETAILS` r
    LEFT JOIN `SILVER_LAYER.SILVER_USER` u ON r.USERID = u.USER_ID;

-- ============================================================
-- 1.35 SILVER_ORDER_ENGAGE_HISTORY (NEW)
-- Grain: One row per TRACK_ID
-- Business Key: TRACK_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_ORDER_ENGAGE_HISTORY` AS
    SELECT
        h.TRACK_ID,
        h.ORDER_KEY_ID,
        h.USER_ID,
        u.USER_FULL_NAME AS USER_NAME,
        h.ENGAGE_FLAG,
        h.CREATED_DT,
        h.EDITED_DT,
        h.EDITED_BY,
        u_ed.USER_FULL_NAME AS EDITED_BY_NAME,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.TBLORDER_ENGAGE_HISTORY` h
    LEFT JOIN `SILVER_LAYER.SILVER_USER` u ON h.USER_ID = u.USER_ID
    LEFT JOIN `SILVER_LAYER.SILVER_USER` u_ed ON h.EDITED_BY = u_ed.USER_ID;

-- ============================================================
-- 1.36 SILVER_PERFORMANCE_TARGET (NEW)
-- Grain: One row per RECORD_ID
-- Business Key: RECORD_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_PERFORMANCE_TARGET` AS
    SELECT
        p.RECORD_ID,
        p.ORDER_KEY_ID,
        MAX(IF(JSON_VALUE(x, '$.name') = 'teleperTarget',
            SAFE_CAST(JSON_VALUE(x, '$.value') AS FLOAT64), NULL)) AS TELEPER_TARGET,
        MAX(IF(JSON_VALUE(x, '$.name') = 'teledodScore',
            SAFE_CAST(JSON_VALUE(x, '$.value') AS FLOAT64), NULL)) AS TELEDOD_SCORE,
        MAX(IF(JSON_VALUE(x, '$.name') = 'emailperTarget',
            SAFE_CAST(JSON_VALUE(x, '$.value') AS FLOAT64), NULL)) AS EMAILPER_TARGET,
        MAX(IF(JSON_VALUE(x, '$.name') = 'emaildodScore',
            SAFE_CAST(JSON_VALUE(x, '$.value') AS FLOAT64), NULL)) AS EMAILDOD_SCORE,
        MAX(IF(JSON_VALUE(x, '$.name') = 'calldownperTarget',
            SAFE_CAST(JSON_VALUE(x, '$.value') AS FLOAT64), NULL)) AS CALLDOWNPER_TARGET,
        MAX(IF(JSON_VALUE(x, '$.name') = 'calldowndodScore',
            SAFE_CAST(JSON_VALUE(x, '$.value') AS FLOAT64), NULL)) AS CALLDOWNDOD_SCORE,
        MAX(IF(JSON_VALUE(x, '$.name') = 'optinperTarget',
            SAFE_CAST(JSON_VALUE(x, '$.value') AS FLOAT64), NULL)) AS OPTINPER_TARGET,
        MAX(IF(JSON_VALUE(x, '$.name') = 'optindodScore',
            SAFE_CAST(JSON_VALUE(x, '$.value') AS FLOAT64), NULL)) AS OPTINDOD_SCORE,
        MAX(IF(JSON_VALUE(x, '$.name') = 'cdperTarget',
            SAFE_CAST(JSON_VALUE(x, '$.value') AS FLOAT64), NULL)) AS CDPER_TARGET,
        MAX(IF(JSON_VALUE(x, '$.name') = 'cddodScore',
            SAFE_CAST(JSON_VALUE(x, '$.value') AS FLOAT64), NULL)) AS CDDOD_SCORE,
        p.ISEDITLOCKED AS IS_EDIT_LOCKED,
        p.EDITED_DT,
        p.EDITED_BY,
        u.USER_FULL_NAME AS EDITED_BY_NAME,
        p.ISDELETE AS IS_DELETED,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.TBLPERFORMANCETARGET_DETAILS` p
    LEFT JOIN `SILVER_LAYER.SILVER_USER` u    ON p.EDITED_BY = u.USER_ID
    LEFT JOIN UNNEST(JSON_QUERY_ARRAY(TRIM(p.PERFORMANCE_TARGET_PARAMETERS))) AS x
    GROUP BY
        p.RECORD_ID,
        p.ORDER_KEY_ID,
        p.ISEDITLOCKED,
        p.EDITED_DT,
        p.EDITED_BY,
        u.USER_FULL_NAME,
        p.ISDELETE;
-- ============================================================
-- 1.37 SILVER_SMTP_HISTORY_TRACKER (NEW)
-- Grain: One row per TRACK_ID
-- Business Key: TRACK_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_SMTP_HISTORY_TRACKER` AS
    WITH smtp_engage_map AS (
        SELECT 
        EMAIL_ID, 
        CLIENT_ID, 
        LEAD_ID, 
        ENGAGE_ID, 
        CAMPAIGN_KEY_ID
        FROM `BRONZE_LAYER.TBLSMTP_ENGAGE_MAPPING`
        QUALIFY ROW_NUMBER() OVER (PARTITION BY EMAIL_ID, CLIENT_ID ORDER BY ID DESC) = 1
    )
    SELECT
        s.TRACK_ID,
        s.RECORD_ID,
        m.LEAD_ID,
        m.ENGAGE_ID,
        m.CAMPAIGN_KEY_ID,
        s.CLIENT_ID,
        CASE WHEN REGEXP_CONTAINS(TRIM(LOWER(s.EMAIL_ID)),r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'  )  
            THEN TRIM(LOWER(s.EMAIL_ID))  ELSE   'Not Availavble' END AS EMAIL_ID,
        s.IDATE,
        TRIM(s.REASON_CODE) AS REASON_CODE,
        TRIM(s.FINAL_STATUS) AS FINAL_STATUS,
        INITCAP(TRIM(s.EBB_TEAM)) AS EBB_TEAM,
        LOWER(TRIM(s.SLOT_TYPE)) AS SLOT_TYPE,
        TRIM(s.SLOT_TIME) AS SLOT_TIME,
        s.AUTOUPLOAD_DT,
        s.UPLOADED_DT,
        s.UPLOADED_BY,
        u.USER_FULL_NAME AS UPLOADED_BY_NAME,
        s.ISVERIFICATIONTERMEXPIRED AS IS_VERIFICATION_TERM_EXPIRED,
        s.ISDELETE AS IS_DELETED,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.TBLSMTPAUDIT_DETAILS_TRACKER_V3` s
     JOIN `smtp_engage_map` m ON s.EMAIL_ID = m.EMAIL_ID AND s.CLIENT_ID = m.CLIENT_ID
     JOIN `SILVER_LAYER.SILVER_USER` u ON s.UPLOADED_BY = u.USER_ID;

-- ============================================================
-- 1.38 SILVER_QA_HISTORY_TRACKER (NEW)
-- Grain: One row per TRACK_ID
-- Business Key: TRACK_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_QA_HISTORY_TRACKER` AS
     SELECT
        q.TRACK_ID,
        q.RECORD_ID,
        q.ENGAGE_ID,
        q.AUDITSTATUS_ID,
        qas.QASTATUS_DESC AS AUDITSTATUS_DESC,
        q.PRIMARYREASON_ID,
        pr.QAPRIMARYREASON_DESC AS PRIMARYREASON_DESC,
        q.SECONDARYREASON_ID,
        q.CALLRATING_ID,
        cr.QACALLRATING_DESC AS CALLRATING_DESC,
        q.SEGMENT_ID,
        sg.QASEGMENT_DESC AS SEGMENT_DESC,
        q.CALLSTATUS_ID,
        cs.CALL_STATUS AS CALLSTATUS_DESC,
        INITCAP(TRIM(q.COMMENTS)) AS COMMENTS,
        TRIM(q.VERIFIEDNUMBER) AS VERIFIEDNUMBER,
        q.PRODUCTIVITY,
        q.LEAD_GENERATION_DATE,
        case when q.CALL_DURATION is null then 'NA' else q.CALL_DURATION end as CALL_DURATION,
        q.REWORKABLE,
        q.EDITED_DT,
        q.EDITED_BY,
        u.USER_FULL_NAME AS EDITED_BY_NAME,
        q.ISDELETE AS IS_DELETED,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.TBLQUALITYAUDIT_DETAILS_TRACKER` q
     JOIN `BRONZE_LAYER.MST_TBLQUALITYAUDIT_STATUS` qas ON qas.QASTATUS_ID = q.AUDITSTATUS_ID
     JOIN `BRONZE_LAYER.MST_TBLQUALITYAUDIT_PRIMARY_REASON` pr ON pr.QAPRIMARYREASON_ID = q.PRIMARYREASON_ID
     JOIN `BRONZE_LAYER.MST_TBLQUALITYAUDIT_CALLRATING` cr ON cr.QACALLRATING_ID = q.CALLRATING_ID
     JOIN `BRONZE_LAYER.MST_TBLQUALITYAUDIT_SEGMENT` sg ON sg.QASEGMENT_ID = q.SEGMENT_ID
     JOIN `BRONZE_LAYER.MST_TBLQUALITYAUDIT_CALLSTATUS` cs ON cs.CALLSTATUS_ID = q.CALLSTATUS_ID
     JOIN `SILVER_LAYER.SILVER_USER` u ON q.EDITED_BY = u.USER_ID;

-- ============================================================
-- 1.39 SILVER_CLIENT_HISTORY (NEW)
-- Grain: One row per RECORD_ID
-- Business Key: RECORD_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_CLIENT_HISTORY` AS
    SELECT
        c.RECORD_ID,
        c.CLIENT_ID,
        UPPER(TRIM(c.CLIENT_CODE)) AS CLIENT_CODE,
        upper(TRIM(c.CLIENT_NAME)) AS CLIENT_NAME,
        UPPER(TRIM(c.CLIENT_ABBREVIATION)) AS CLIENT_ABBREVIATION,
        INITCAP(TRIM(c.SENDERS_NAME)) AS SENDERS_NAME,
        CASE  WHEN REGEXP_CONTAINS(TRIM(LOWER(SENDERS_EMAIL)),r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'  )  
            THEN TRIM(LOWER(SENDERS_EMAIL))  ELSE   'Not Available' END AS SENDERS_EMAIL,
        c.CREATED_DT,
        c.CREATED_BY,
        u_cr.USER_FULL_NAME AS CREATED_BY_NAME,
        c.EDITED_DT,
        c.EDITED_BY,
        u_ed.USER_FULL_NAME AS EDITED_BY_NAME,
        c.ISACTIVE AS IS_ACTIVE,
        c.SMTPAUTO_STATUS,
        c.STATUS_EDITED_BY,
        u_st.USER_FULL_NAME AS STATUS_EDITED_BY_NAME,
        c.VERSION_ID,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.MST_TBLCLIENTS_TRACKER` c
    LEFT JOIN `SILVER_LAYER.SILVER_USER` u_cr ON c.CREATED_BY = u_cr.USER_ID
    LEFT JOIN `SILVER_LAYER.SILVER_USER` u_ed ON c.EDITED_BY = u_ed.USER_ID
    LEFT JOIN `SILVER_LAYER.SILVER_USER` u_st ON c.STATUS_EDITED_BY = u_st.USER_ID;

-- ============================================================
-- 1.40 SILVER_ORDER_SUPPRESSION_RULE (NEW)
-- Grain: One row per OS_SUPRESSION_ID
-- Business Key: OS_SUPRESSION_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_ORDER_SUPPRESSION_RULE` AS
    SELECT
        s.OS_SUPRESSION_ID,
        s.ORDER_KEY_ID,
        initcap(TRIM(s.FILTER_NAME)) AS FILTER_NAME,
        s.LEADTYPE_ID,
        lt.LEADTYPE_DESC,
        TRIM(s.DATAFIELD_IDENTIFIER) AS DATAFIELD_IDENTIFIER,
        TRIM(s.DATA_VALUE1) AS DATA_VALUE1,
        TRIM(s.DATA_VALUE) AS DATA_VALUE,
        s.SUPRESS_UNTIL_DT,
        s.SUPRESS_REASON_ID,
        sr.SUPRESSREASON_DESC AS SUPPRESS_REASON_DESC,
        s.ISINDEFINITESUPRESSED AS IS_INDEFINITE_SUPPRESSED,
        s.SUPRESSRULE_TYPE_ID,
        s.INSERTED_DT,
        s.INSERTED_BY,
        u.USER_FULL_NAME AS INSERTED_BY_NAME,
        s.ISACTIVE AS IS_ACTIVE,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.TBLORDERSPECIFIC_DATASUPRESSION_TBD` s
    LEFT JOIN `BRONZE_LAYER.MST_TBLLEADTYPES` lt ON CAST(s.LEADTYPE_ID AS INT64) = lt.LEADTYPE_ID
    LEFT JOIN `BRONZE_LAYER.MST_TBLLEADSUPRESS_REASON` sr ON s.SUPRESS_REASON_ID = sr.SUPRESSREASON_ID
    LEFT JOIN `SILVER_LAYER.SILVER_USER` u ON s.INSERTED_BY  = u.USER_ID ;
-- ============================================================
-- 1.41 SILVER_REGION_USER_MAPPING (NEW)
-- Grain: One row per REGION_USERMAP_ID
-- Business Key: REGION_USERMAP_ID
-- ============================================================
CREATE OR REPLACE TABLE `SILVER_LAYER.SILVER_REGION_USER_MAPPING` AS
    SELECT
        m.REGION_USERMAP_ID,
        m.USER_ID,
        u.USER_FULL_NAME AS USER_NAME,
        m.REGION_ID,
        r.REGION_DESC,
        m.NEW,
        m.NEWEDITED,
        m.LIVE,
        m.LIVEEDITED,
        m.LIVEUNPAUSED,
        m.PAUSED,
        m.COMPLETEINT,
        m.READYTOBILL,
        m.BILLED,
        m.PARTIALLYBILLED,
        m.REBILLED,
        m.PAID,
        m.COMPLETE,
        m.CANCELLED,
        m.OPSVERIFIED,
        m.CREATED_DT,
        m.CREATED_BY,
        m.EDITED_DT,
        m.EDITED_BY,
        m.ISACTIVE AS IS_ACTIVE,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER_ODM.MST_TBLREGIONUSERMAPPING` m
    LEFT JOIN `SILVER_LAYER.SILVER_USER` u ON m.USER_ID = u.USER_ID
    LEFT JOIN `BRONZE_LAYER_ODM.MST_TBLREGIONS` r ON m.REGION_ID = r.REGION_ID;
