SELECT
        u.USER_ID, IFNULL(CAST(U.PUSER_ID AS INT64), 0) AS PARENT_USER_ID,
        TRIM(u.USER_EMPLOYEE_ID) AS USER_EMPLOYEE_ID,
        TRIM( INITCAP( REGEXP_REPLACE(u.USER_FIRSTNAME, r'[^A-Za-z0-9]+', ' ') ) ) AS USER_FIRSTNAME,
        TRIM( INITCAP( REGEXP_REPLACE(u.USER_MIDDLENAME, r'[^A-Za-z0-9]+', ' ') ) ) AS USER_MIDDLENAME,
        TRIM( INITCAP( REGEXP_REPLACE(u.USER_LASTNAME, r'[^A-Za-z0-9]+', ' ') ) ) AS USER_LASTNAME,
        TRIM( INITCAP( REGEXP_REPLACE( REGEXP_REPLACE(u.USER_FIRSTNAME, r'[^A-Za-z0-9]+', ' '), r'\s+', ' ' ) ) ) || 
        COALESCE( ' ' || TRIM( INITCAP( REGEXP_REPLACE( REGEXP_REPLACE(u.USER_LASTNAME, r'[^A-Za-z0-9]+', ' '), r'\s+', ' ' ) ) ), '' ) AS USER_FULL_NAME,
        CASE  WHEN REGEXP_CONTAINS(TRIM(LOWER(u.USER_EMAIL)),r'^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'  )  
            THEN TRIM(LOWER(u.USER_EMAIL))  ELSE   'Not Available' END AS USER_EMAIL,
        u.DEPARTMENT_ID,
        TRIM(d.DEPARTMENT_DESC) AS DEPARTMENT_DESC,
        u.PROLE_ID,
        TRIM(r.PROLE_DESC) AS PROCESS_ROLE_DESC,
        CASE WHEN NULLIF(TRIM(u.USER_COUNTRYCODE), '') IS NULL THEN NULL
        WHEN TRIM(u.USER_COUNTRYCODE) IN ('0', '00') THEN '00'
        WHEN REGEXP_CONTAINS(TRIM(u.USER_COUNTRYCODE), r'^\+?[0-9]{1,3}$')
        THEN REGEXP_REPLACE(TRIM(u.USER_COUNTRYCODE), r'^\+', '')
        ELSE '00' END AS USER_COUNTRYCODE ,
        CASE WHEN NULLIF(TRIM(u.USER_MOBILE), '') IS NULL THEN NULL
            WHEN REGEXP_CONTAINS(REGEXP_REPLACE(TRIM(u.USER_MOBILE), r'[^0-9]', ''),r'^[1-9][0-9]{9,14}$')  
            THEN REGEXP_REPLACE(TRIM(u.USER_MOBILE), r'[^0-9]', '')  ELSE '0000000000' END AS USER_MOBILE,
        u.ISWFH AS IS_WORK_FROM_HOME,
        u.ISCUSTOMACCESS AS IS_CUSTOM_ACCESS,
        u.ISATAQUALITYAUDITOR AS IS_QA_AUDITOR,
        u.PRDSUBGROUP_ID,u.P_ATA_ID,
        u.ISACTIVE AS IS_ACTIVE,
        CASE WHEN u.EXTENSION_ID IS NULL OR u.EXTENSION_ID <= 0 THEN '0' ELSE CAST(u.EXTENSION_ID AS STRING) END AS EXTENSION_ID,
        u.CREATED_DT,
        u.EDITED_DT,
        u.EDITED_BY,
        CURRENT_TIMESTAMP() AS SOURCE_LOADED_AT
    FROM `BRONZE_LAYER.MST_TBLUSERS` u
    JOIN `BRONZE_LAYER_ODM.MST_TBLDEPARTMENT` d
        ON u.DEPARTMENT_ID = d.DEPARTMENT_ID
    JOIN `BRONZE_LAYER_ODM.MST_TBLUSER_PROCESSROLES` r
        ON u.PROLE_ID = r.PROLE_ID ;